client/stylesheets/setup.scss, imports/client/components/AccountForm.jsx, imports/client/components/Celebration.jsx, imports/client/components/HuntListPage.jsx, imports/client/components/NotificationCenter.jsx, imports/client/components/ProfilePage.jsx, imports/client/components/PuzzlePage.jsx, imports/client/components/SetupPage.jsx, imports/lib/active-operator-role.js, imports/lib/models/announcements.js, imports/lib/models/facade.js, imports/lib/models/guess.js, imports/lib/models/hunts.js, imports/lib/models/puzzles.js, imports/lib/models/settings.js, imports/lib/roles.js, imports/lib/schemas/settings.js, imports/server/api_keys.js, imports/server/gdrive-client-refresher.js, imports/server/gdrive.js, imports/server/migrations/18-rename-gdrive-template.js, imports/server/models/api_keys.js, imports/server/observability.js, imports/server/operator.js, imports/server/puzzle.js, imports/server/setup.js, imports/server/slack-methods.js, imports/server/slack.js, imports/server/users.js
This changeset does rather a lot, so I've tried to break it into a bunch of commits piece-by-piece, which is also how I suggest you review it.  The first several commits in this series are already included in #161, which fixes several bugs that I discovered while building out and testing everything in this PR.
The high-level goal of this PR is to expose in the webui most of the functionality that we've previously abused the Meteor shell to realize.
To that end, the new setup page provides:
* step-by-step guidance around the three major pieces of our Google integration: OAuth client, Drive connection, and document templates.  
* a way to configure Slack integration from the web
* circuit breakers for both the Google and Slack integrations, so you can disable them without having to blank …
=> Make a bunch more things configurable in SetupPage

imports/client/components/AccountForm.jsx, imports/client/components/Celebration.jsx, imports/client/components/NotificationCenter.jsx, imports/client/components/ProfilePage.jsx, imports/client/components/PuzzlePage.jsx
I went through a bunch of our workflows with the browser console and server console open and looked for anything that seemed out of place.  I found several things:
* `saveProfile` takes one more argument than we were passing to it from the call in the setup flow, which was making new signups lack a profile
* `dismissAfter` is not a thing and we should remove it
* `NotificationCenter`'s propTypes were missing one layer of objects
* the `autoFocus` prop takes a boolean value, not a string value
* Unlike everything else, the React [props for `aria-*` should be kebab-case, not camelCase](https://reactjs.org/docs/accessibility.html)
r? @ebroder
=> Assorted fixes

cloudformation/jolly-roger.yaml, package.json
Now that the Docker repo is public, it's no longer needed.
=> Eliminate the private docker registry

imports/client/components/ConnectionStatus.jsx
If we rendered more than once a second, we might trigger very frequent
repaints.  This change makes sure that we don't auto-repaint from timeout
triggers more than once a second, closing out an old TODO item.
=> Debounce connection status refresh

imports/client/components/Gravatar.jsx, imports/client/components/ProfilePage.jsx, package-lock.json, package.json
We already have email addresses from profiles, so to get profile pictures from gravatar we basically just have to add an MD5 implementation (~4kB).  While many people have Google accounts which they link to their jolly-roger accounts, we don't explicitly require them, and a Google integration might involve serverside pieces, whereas the gravatar integration could be entirely clientside, so I favored using gravatars over Google profile pictures for a first-pass profile image.  If we decide we want to, we could always build such a Google integration in as well for people who link Google accounts.
I don't actually feel strongly about if this is useful or not, but I found an old TODO and figured this was low-hanging fruit so I threw it together.
=> Add gravatars to profile page

cloudformation/jolly-roger.yaml
The CloudFormation template previously had a hard-coded set of AMIs to
use, but that gets stale quickly. Instead, use a custom resource backed
by a Lambda function to lookup the latest AMIs whenever the
CloudFormation template gets updated.
(This won't, e.g., upgrade instances if they're replaced between
CloudFormation runs, but it's still better than a fixed AMI.)
I haven't been able to test this in prod yet, because the stack is currently stuck due to a bug in an earlier version. I think it'll eventually reset after enough time.
=> Switch to using a custom resource for AMI lookups

imports/client/components/App.jsx, imports/client/components/SplashPage.jsx
As it turns out, browsers don't automatically fetch @2x images; you have
to tell them to do it. This mirrors how we handled retina image tags for
the Head Hunters website.
=> Actually use retina-scale images

.meteor/packages, .meteor/versions, imports/client/components/ProfilePage.jsx, imports/lib/models/proptypes.js, imports/lib/schemas/announcements.js, imports/lib/schemas/base.js, imports/lib/schemas/chats.js, imports/lib/schemas/document_permissions.js, imports/lib/schemas/documents.js, imports/lib/schemas/feature_flags.js, imports/lib/schemas/guess.js, imports/lib/schemas/hunts.js, imports/lib/schemas/pending_announcements.js, imports/lib/schemas/profiles.js, imports/lib/schemas/puzzles.js, imports/lib/schemas/settings.js, imports/lib/schemas/tags.js, imports/lib/schemas/users.js, imports/server/schemas/api_keys.js, imports/server/schemas/lock.js, imports/server/schemas/servers.js, imports/server/schemas/subscribers.js, package-lock.json, package.json
The aldeed:simple-schema atmosphere package has been replaced with the simpl-schema NPM package. Catch us up and make the requisite API updates for a few rounds of backwards-incompatible changes.
The version numbering here is kind of confusing - when the package moved to NPM, the version numbering reset, so simpl-schema v1.5.3 is actually 2 major version bumps ahead of the version we're currently running (aldeed:simple-schema@1.5.4 :see_no_evil:).
The requisite changlog entries are the [2.0.0 pseudo-update for the atmosphere package](https://github.com/aldeed/meteor-simple-schema/blob/master/CHANGELOG.md#200), and the [full changelog for the NPM package](https://github.com/aldeed/simple-schema-js/blob/master/CHANGELOG.md).
Here's a quick run through of how those translated to code …
=> Upgrade to simpl-schema v1.5.3

client/stylesheets/puzzle.scss, imports/client/components/Puzzle.jsx
There was a suggestion from a few years ago that this might make the view a bit more compact. I'm a little worried about learning curve (I added a title tooltip to try and tame that a bit, not sure it'll actually be enough), but it does give us some pixels back.
Here's two screenshots to compare:
Thoughts?
=> Replace "(puzzle)" link with puzzle piece icon

client/stylesheets/puzzlelist.scss, imports/client/components/PuzzleListPage.jsx
Search bar is moved inline with the other view filters. View filters all
become toggle buttons instead of the nav pills + checkbox thing previously.
Add puzzle button is now on its own row.
On small screens, the announcements/guesses/hunters links move to the top.
Before, mobile:
After, mobile:
Before, desktop:
After, desktop:
=> Redesign view filters / top UI on puzzle list page

client/stylesheets/puzzle.css, client/stylesheets/puzzle.scss
Why was there a separate puzzle.css file?  I'm not sure, but I've folded it's
contents back into the .scss file.
All the rows should now be 32px tall, whether they have tags or not.
Fixes #189.
Before:
After:
=> Reduce puzzle list padding, set min height, center

imports/lib/models/puzzles.js, imports/server/fixture.js, imports/server/puzzle.js
This tries to ensure that the list of tags doesn't end up with
duplicates, preferably on the server side, but in the worst case
cleaning them up client-side.
Fixes #180.
I ended up doing this instead of consolidating around `addTag[s]ToPuzzle` and `removeTag[s]FromPuzzle` because you'd still have to compute what you were adding/removing and that seemed annoying.
=> Make sure list of tag IDs is unique

imports/client/components/GuessQueuePage.jsx, imports/client/components/HuntListPage.jsx, imports/client/components/NotificationCenter.jsx, imports/lib/schemas/hunts.js, imports/model-helpers.js, package-lock.json, package.json
I decided to use Mustache because it felt better than coming up with my own variable substitution code. I think that this does accomplish what we need, although it's not the most user-friendly thing imaginable. Maybe that's OK.
Minor note: It looks like the [API in question](https://developer.mozilla.org/en-US/docs/Web/API/URL) may not be supported in IE11, so we may want to grab a polyfill (a la https://www.npmjs.com/package/url-polyfill)
Fixes #181.
=> Make it possible to link directly to guess submission page

imports/client/components/ProfilePage.jsx, imports/lib/schemas/profiles.js
Per Slack conversation with @ebroder:
In practice, JR requires Slack handles.  Update the profile form to reflect this.  Also, move Slack handle above (still optional) phone number.
=> Require Slack handle in profile form

client/stylesheets/puzzlelist.scss
Fixes two glitches in puzzle list controls CSS:
- On Safari, the text field always started on the next line instead of flowing alongside the buttons.
- The text field did not expand to fill available space when the window was narrower than 768px but still wide enough for the buttons and text field on the same line.
=> Puzzle list control CSS fixes.

client/stylesheets/puzzle.scss, imports/client/components/PuzzlePage.jsx
Chat was difficult to read on platforms with frameless windows, as the text ran into the window edge.  This adds slight padding to chat messages and adjusts the textarea to match.  Also applies similar padding to related puzzles.
Additionally, increases the line-height on the textarea to accommodate its font size.  Unfortunately, the textarea uses a font-size of 16px to prevent iOS Safari from zooming, so the textarea formatting doesn't precisely match the messages above it (at font-size 14px).  One workaround would be applying the 16px font-size only in mobile Safari.
=> Add horizontal padding in side panes

client/stylesheets/guessqueue.scss, client/stylesheets/notifications.scss, imports/client/components/GuessQueuePage.jsx, imports/client/components/NotificationCenter.jsx
In particular, break display names and answer queue submissions in the
notifications and the guess queue page.
Fixes #185.
Before:
After:
=> Make more user-provided content line-breakable

client/stylesheets/puzzle.scss, imports/client/components/DeepLink.jsx, imports/client/components/Documents.jsx, imports/client/components/PuzzlePage.jsx
Addresses #192.
On tablets and phones, Google loads a static html view in browsers, instead of the live editable version and I have found no way to force it do otherwise.  (On phones this makes no difference as there isn't space for the document anyway.)  As a workaround, this offers a link to open the document in the native app.  The link is not shown on devices with fine pointer control and is always shown on windows too small to load the document (as it always was).  On iPads, it's then possible to keep Safari open in narrow mode side-by-side with the native Sheets app, replicating the full JR experience.
(The static view unfortunately also renders slightly incorrectly, but this appears to simply be a bug in Google Sheets: The tab switcher is absolutely positioned as through the title …
=> Improved functionality on tablets.

imports/client/components/PuzzlePage.jsx
Puzzle page now refers to "1 guess" instead of "1 guesses"
=> Use singular guess

imports/client/components/PuzzleListPage.jsx
It's documented at
https://react-bootstrap.github.io/components/forms/#forms-props-form-control as
only working with callback refs, so we can't use the `React.createRef()` API
here.
This was breaking autofocus on the input bar on page load.  It was also throwing a console warning on every pageload of the puzzle list page.
=> Swap back to callback refs for `FormControl`

client/stylesheets/puzzle.scss
Addresses #214.
* Drop that kinda-grey background; it's not helpful.
* Steal a couple pixels back from the gutters.
* Also steal those pixels back from the related puzzles section.
* Make chat timestamps less emphasized -- smaller text, lighter grey
We should also increase the template google spreadsheet's default font size to ~14px (10.5pt).
=> Tweak chat pane

client/stylesheets/puzzlelist.scss, imports/client/components/PuzzleListPage.jsx
Addresses #220
On the puzzle list page (hunt landing page) move list of links to the top and style to emphasize that they are navigation and not part of the filter controls.  Leave "Add puzzle" button inline with the filter controls.  Adjust flow of the remaining controls.
CSS is a little quick - I'm sure someone more skilled with flexbox could do this more elegantly.
=> Style list of links as navigation

client/stylesheets/puzzle.scss, imports/client/components/PuzzlePage.jsx
Three fixes:
- Viewer count and external links can no longer be broken by line wraps
- The metadata action row could be slightly too long on narrow phones (or iPad split view).  Adjusted the flex to wrap in the worst case and solve the problem in most cases by simply hiding the external link icons.  (I would rather hide the number of guesses so far, but that's actually a little trickier, so this is fine for now.)
- Match the chat textarea padding to the content above it.
=> Fix CSS glitches involving breaks and wrapping

imports/client/components/Puzzle.jsx, imports/client/components/PuzzleListPage.jsx, imports/client/components/PuzzlePage.jsx, imports/client/components/RelatedPuzzleGroups.jsx, imports/client/components/puzzleInterestingness.js
I've seen both of these callsites crash the React renderer.  I'm hopeful
they're the last for this particular failure mode; I don't think I see other
places where we're doing the client-side join from tag id -> `Tag`.
=> Guard more instances of tag name lookup by id against weird load order

package-lock.json, package.json
Addresses [CVE-2019-8331](https://nvd.nist.gov/vuln/detail/CVE-2019-8331), which I think probably doesn't affect us, but this will make Github stop yelling at me.
=> Bump bootstrap version

imports/lib/schemas/base.ts, imports/lib/schemas/typedSchemas.ts
We need to have _id as part of the type so that we can access the field,
but we don't want to declare it as part of the schema. The validation
logic in collection2 doesn't handle the fact that _id is auto-populated
well, so it causes spurious validation errors.
=> Exclude the _id field from the SimpleSchema

imports/lib/models/base.ts
Because we're using SimpleSchema autoValues in a lot of cases, those
fields aren't actually required for inserts. But the type specification
for insert requires a full object, and there's no way to communicate
through the types that some types are auto-populated (i.e. required to
be present on read, but not on write).
Work around this by overriding the type for insert to be significantly
looser. This is actually loose to the point of being technically unsafe,
but there's no way in the type layer to tell which fields have autoValue
specified and which don't.
=> Loosen the types on collection.insert

client/stylesheets/breadcrumbs.scss, imports/client/components/App.tsx
LinkContainer decides whether or not a given link is active, and then
forces a value for the active prop onto its child (ugh). By default, it
considers itself "active" even when its on a child page, but
onlyActiveOnIndex overrides that behavior, ensuring that it only
considers itself active unless we're actually on /hunts/:hunt (which we
never are - we always redirect to puzzles, but it's easy to go from
active=false to active=true and hard to go the other way).
(Also fix the styling, which was getting mis-applied to the wrong
elements)
=> Fix rendering of breadcrumbs, broken in #256

imports/flags.ts, imports/server/announcements.ts, imports/server/ansible.ts, imports/server/api_keys.ts, imports/server/chat.ts, imports/server/feature_flags.ts, imports/server/guesses.ts, imports/server/hunts.ts, imports/server/operator.ts, imports/server/profile.ts, imports/server/puzzle.ts, imports/server/setup.ts, imports/server/slack-methods.ts, imports/server/subscribers.ts, package-lock.json, package.json
Now that `check` is annotated as an assertion function, we can get
sufficient type information just from the check calls. By annotating the
argument types to unknown, we can more accurately reflect that we don't
yet know the types.
=> Switch meteor method arguments to unknown

client/stylesheets/puzzle.scss, imports/client/components/PuzzlePage.tsx
- Increase the lineHeight in the chat textarea to improve consistency and legibility
- Adds padding to the placeholder text that appears when the chat history is empty (missed in #213)
=> Minor improvements to chat style

client/stylesheets/puzzle.scss
- Correct an overly restrictive media query from #225, used to minimize content for very narrow windows.
- Allow answers to break. Previously, long answers could force the title to wrap poorly. While not a perfect solution, simply allowing the answer to break (combined with the existing flex behavior) results in a reasonable layout. This change primarily affects mobile and puzzles with exceptionally long answers.
=> Minor improvements to puzzle metadata style

imports/client/components/HuntApp.tsx, imports/client/components/UserInvitePage.tsx, package-lock.json, package.json
This lets us get rid of our direct dependency on prop-types, although it doesn't remove it from the bundle since most React libraries ship with prop-types definitions.
(I could be convinced that this isn't worth merging, since it doesn't actually shrink the bundle at all, but it seems like a nice cleanup, and gets rid of the last usage of legacy context)
=> Switch to withRouter

imports/client/components/AnnouncementsPage.tsx, imports/client/components/HuntApp.tsx, imports/client/components/NotificationCenter.tsx, imports/client/components/PuzzlePage.tsx
Per conversation with @ebroder we aren't likely to change these four uses of dangerouslySetInnerHTML, so the warnings being generated aren't drawing attention to anything useful. I suggest adding the eslint-disable as an acknowledgment of the issue and moving on without the warnings.
=> Suppress 4 eslint warnings for react/no-danger

imports/client/components/PuzzlePage.tsx
Per Issue #234, related puzzles are most useful for meta puzzles. For other puzzles, the information should be available, but the space may be better devoted to chat.
This automatically collapses related puzzles for puzzles without meta-related tags. When navigating between puzzles, related puzzles will never be collapsed automatically (so related puzzles stays open when navigating from a meta to a puzzle), but may be expanded (so related puzzles is opened automatically when navigating from a puzzle to a meta, though currently there are no links to other puzzles other than in the related pane, so it was almost certainly already open).
As an example, clicking Spotted Tower from the hunt landing page will cause the related puzzles pane to open, but clicking Topsy Turvy from the same page …
=> Suggestion: Automatically collapse related puzzles if unlikely to be useful

client/stylesheets/puzzle.scss, imports/client/components/Documents.tsx, imports/client/components/PuzzlePage.tsx
Despite doing the same thing (opening a modal), the viewers and guess button have different presentations. The former is an unstyled link with a popover and the latter is a button. Since the action isn't navigation, standardize on button. Also move the viewers button to the bottom row, as it doesn't make a lot of sense inline with the title and contributes to needless line breaks there.
Change the text for both buttons to be more concise (and invoke a verb). The viewers button now reads "See \<n\> hunter(s)" while the guess button reads either "Guess (\<n\> so far)" or "See \<n\> guess(es)" depending on the solve status.
Change the labels for document links to reflect Google's naming convention (which conveniently shortens them) and use different icons for sheets and docs.
With those …
=> Relocate viewers in puzzle metadata

imports/client/components/NotificationCenter.tsx
This is a suggested implementation of #235, adding a JR link to guess notifications. Adds separate buttons, each with a tooltip, for opening the JR page or the puzzle.
Per conversation on #235, this adopts the convention of using the external link icon for puzzle links and further uses the puzzle piece icon for JR links. If we adopt this convention, we should replace the icons generated by puzzle listings with the external link icon (probably a good idea anyway).
=> Suggestion: Add JR link to guess notification

imports/client/components/PuzzlePage.tsx
Per conversation with @ebroder, we're going with puzzle-piece for puzzle links. Replaces #276.
=> Replace external link icon with puzzle piece

client/stylesheets/puzzle.scss, imports/client/components/PuzzlePage.tsx, imports/client/components/SplitPanePlus.tsx
Rewrite SplitPanePlus to be fully controlled, with associtated rewiring of PuzzlePage. SplitPanePlus now has somewhat different (but hopefully more intuitive) behaviors around the size prop than the underlying SplitPane. Automatic classes are now assigned to individual collapsed panes and the resizer instead of to the parent SplitPane. Min and max sizes are now respected during resize.
Fixes several bugs (The first three could occur whenever Related Puzzles was collapsed):
- Clicking and immediately releasing the resizer when a secondary pane is collapsed no longer clears the collapse state.
- Dragging a collapsed pane and releasing it within the auto-collapse zone no longer clears the collapse state.
- The primary pane no longer overfills the parent container when the secondary pane is …
=> Rewrite SplitPanePlus as fully controlled

client/stylesheets/index.css
Before this patch, buttons like the "See 2 guesses" button would get the emoji
block number for digits.
=> Don't prefer emoji over sans-serif for most content

imports/lib/schemas/puzzles.ts, imports/lib/schemas/typedSchemas.ts, imports/server/guesses.ts
`autoValue` is confusing and sometimes gets the whole array (on document
creation?) and sometimes gets just the element that changed (a string, in this
case).  Loosen the types and do some runtime type-checking to deal with it.
Fix a typo in guesses where we wouldn't pull the guess from `answers` when
transitioning from correct to any other state.
=> Fix autovalue stuff in puzzles around arrays

client/stylesheets/app.scss, client/stylesheets/index.css, client/stylesheets/puzzle.scss, imports/client/components/App.tsx, imports/client/components/PuzzlePage.tsx
If we're a bit more clever with our CSS (and accept one very minor UI change - namely that the disconnect alert is always at a fixed non-scrolling position), then we can have fixed markup for the app framework and only need custom markup and styling for the actual puzzle page.
This gets rid of the fairly awkward hack where the App component was going digging through the resolved routes under it (which will make the react-router v5 upgrade easier).
=> Get rid of desiredLayout hack

imports/client/components/PuzzleListPage.tsx
I'm not sure why this was disjunctive before, but it doesn't make a ton of
sense to me now.  Now, if you provide multiple space-separated search keys, the
filter will show only puzzles that match all of the keys in some way, which I
think aligns better with "typing is specifying additional constraints over what
we intend to show", and means that typing more should never result in seeing a
larger result set.
Additionally, arbitrary substring search in puzzle title might be a bit much.
We can preseve the above property and narrow in more quickly if we do word-prefix
search instead.  We'll use this for puzzle titles, but answers and tags are often
written with no whitespace, so we'll stick with arbitrary substring matching for
those.
=> Tweak search on PuzzleListPage

imports/client/components/DeepLink.tsx, imports/client/components/NotificationCenter.tsx, imports/client/components/ProfileList.tsx, imports/client/components/Puzzle.tsx, imports/client/components/PuzzleListPage.tsx, imports/client/components/PuzzleModalForm.tsx, imports/client/components/PuzzlePage.tsx, imports/client/components/RelatedPuzzleGroups.tsx, imports/client/components/TagEditor.tsx, imports/lib/models/base.ts, imports/lib/models/hunts.ts, imports/lib/models/pending_announcements.ts, imports/lib/models/puzzles.ts, imports/model-helpers.ts, imports/server/accounts.ts, imports/server/gdrive.ts, imports/server/hunts.ts, imports/server/puzzle.ts, imports/server/subscribers.ts
Mostly a lift of #279 with a couple merge fixes and guarding against null `Meteor.user().hunts`
in the `hunt.join` allow rule (which is why we had to revert #279).
=> Replace lots of underscore with native equivalents

.eslintrc.json, .github/workflows/test.yml, .meteor/packages, .meteor/versions, imports/client/components/Routes.tsx, imports/client/main.tsx, imports/server/models/lock.ts, package-lock.json, package.json, tests/acceptance/authentication.tsx, tests/acceptance/lib.ts, tests/down/package.json, tests/main.ts, tsconfig.json, types/deanius:promise/meteor.d.ts, types/google-oauth/index.d.ts, types/nicolaslopezj:roles/roles.d.ts, types/oauth/index.d.ts, types/percolate:migrations/migrations.d.ts, types/sha/sha.d.ts, types/xolvio:cleaner/cleaner.d.ts
Meteor's client/server split in testing makes this a little annoying to wire up. In particular, I wanted to be able to define server-side helper methods for client-side tests, but that meant that a single file was loaded on both client and server _and_ needed some client-only imports, hence the slightly messy use of require.
I think this is prooobably still a good idea but it's definitely a bit fiddly.
=> Set up a basic test suite

client/stylesheets/setup.scss, imports/client/components/ProfilePage.tsx, imports/client/components/SetupPage.tsx, imports/client/discord.ts, imports/lib/discord.ts, imports/lib/roles.ts, imports/lib/schemas/discord_account.ts, imports/lib/schemas/profiles.ts, imports/lib/schemas/settings.ts, imports/server/discord.ts, imports/server/profile.ts, imports/server/setup.ts, server/main.ts, types/oauth/index.d.ts
This is a rather-large patchset that implements a baseline Discord integration capable of automating guild invitations.
The first commit adds server configuration at `/setup`.  We introduce a new `ServiceConfiguration` with `{ name: 'discord' }` to hold the OAuth client ID and client secret, following the same general scheme as other OAuth integrations.  We add two new `Settings` keys, `discord.bot` and `discord.guild` to keep track of the bot client token and the guild we intend to this server to help manage.
The second commit implements OAuth2 login, account linking, and guild invitation.  The flow starts on ProfilePage.tsx, traverses the usual Meteor OAuth machinery, and then once a token has been obtained, bottoms out in the Meteor methods in `imports/server/profile.ts`.
Fixes #320.
=> Add Discord server configuration, OAuth flow, and automate guild invitations

imports/client/components/PuzzleListPage.tsx, imports/client/components/PuzzlePage.tsx, imports/client/components/SetupPage.tsx, imports/client/components/SubscriberCount.tsx, imports/server/migrations/26-remove-subcounter-feature-flags.ts, imports/server/migrations/all.ts, imports/server/subscribers.ts
These have been operating stably for years now, and I want to take a hard dep on subscription watching to track presence, so I can show who is in a group audio call and who is just in the text chat.
=> Remove circuit-breakers for subscription counters/watchers

DEVELOPING.md, OPERATION.md, README.md
`README.md` now explains what Jolly Roger is and why you'd want to use it.
`DEVELOPING.md` explains how to set up your own instance for development.
`OPERATION.md` is a stub, but in time should help explain what else you'll need
to bring to run Jolly Roger in anger.
We should probably come up with a new place to write about internals.
=> Rewrite README and split out other documentation by purpose

client/stylesheets/puzzle.scss, imports/client/components/PuzzlePage.tsx
On mobile devices the keyboards often don't have an Enter key, so a separate
"Send" button is needed.
Fixes #287
=> Add `Send` button to chat input area

client/stylesheets/puzzle.scss, imports/client/components/PuzzlePage.tsx
Minor changes to chat controls:
* Style tweaks, including improved control consistency
* Text area always gets focus after submit (previously never)
* Send button disabled when no text entered
* Textarea and button behave as one control, with shared focus and tab-index
Before:
After:
Before with content and focus:
After with content and focus:
=> Polish chat controls

imports/server/garbage-collection.ts, imports/server/subscribers.ts
WebRTC support will also want to be able to clean up any records leaked by
other servers, so extract the periodic cleanup into something reusable.
=> Extract reusable server GC hook registry

imports/lib/models/facade.ts, imports/lib/models/public_settings.ts, imports/lib/schemas/public_settings.ts
"public" here means "published to all clients at all times, no ACLs
whatsoever".  It's a transport mechanism for things you'd put in source code if
you didn't want to support different values in different deployments.
This will be used for WebRTC STUN/TURN server configuration, and could be used
for rebranding.
=> Add `PublicSettings` for server-specific settings that should be public

client/stylesheets/puzzle.scss, imports/client/components/HuntListPage.tsx, imports/client/components/PuzzlePage.tsx, imports/lib/schemas/hunts.ts, imports/server/guesses.ts, imports/server/migrations/27-hunt-has-guess-queue.ts, imports/server/migrations/28-hunt-has-guess-queue.ts, imports/server/migrations/all.ts
This adds a hasGuessQueue attribute to the Hunt model. Said attribute is on by default, so the user guess -> operator approval flow will still be the case for instances unless this is explicitly set by the operator.
When hasGuessQueue is false, users can able to submit answers directly, without the guess UI or operator approval. In that mode, additionally, users can remove answer(s) from the list on the puzzle page (if, e.g. they made a typo the first time).
=> Add mode without guess queue

client/stylesheets/puzzlelist.scss, imports/client/components/HuntListPage.tsx, imports/client/components/PuzzleListPage.tsx, imports/lib/schemas/hunts.ts
Add an optional field to Hunts to store hunt homepage urls, rendered as a link on the puzzle list page. Also, no longer wait for puzzle and tag data to render the hunt navigation links. General cleanup of PuzzleListPage, including removal of redundant and unreferenced markup.
No migration added, as it appears we aren't creating migrations for the creation of optional fields. Please correct me if I'm wrong.
Closes #292
=> Add hunt homepage link to landing pages

client/stylesheets/puzzle.scss, imports/client/components/PuzzleListPage.tsx, imports/client/components/RelatedPuzzleGroup.tsx
Render tagless puzzle groups in the same way as ordinary groups, including collapse behavior. Achieved by giving RelatedPuzzleGroup support for null sharedTag. (Though the .tag class is used to achieve consistent styling, the Tag component has not been extended to support no tag.)
Closes #347
=> Render tagless group consistently

imports/server/fixture.ts
This broke when we added a new required field to the Hunt schema that we didn't
specify in the `createFixtureHunt` method.
=> Fix fixture hunt creation

imports/client/components/FirstUserForm.tsx, imports/client/components/RootRedirector.tsx, imports/client/components/Routes.tsx, imports/client/has_users.ts, imports/server/setup.ts, package.json, tests/acceptance/authentication.tsx, tests/acceptance/lib.ts
It's actually kinda hard to set up a new production Jolly Roger deployment,
since there's no good way to get a meteor shell with a connection to the real
DB to create the first account.  You either have to figure out how to get a
shell hooked up to your production DB (which we don't document), or you have to
bring a row from your development users table via a mongo client, or something else
ridiculous.  We can do better.
This change adds:
* a pseudocollection that simply indicates whether there are any
users in the Meteor users table
* a Meteor method to provision the initial admin user provided there
are no users in the Meteor users table yet
* a page with a form to enter an email address/password to be used with the
aforementioned Meteor method
* logic in the root redirector to send you …
=> Add in-app first-user-creation flow for server admin

client/stylesheets/puzzle.scss, imports/client/components/AuthenticatedRoute.tsx, imports/client/components/CallLinkBox.tsx, imports/client/components/CallSection.tsx, imports/client/components/ChatPeople.tsx, imports/client/components/HuntApp.tsx, imports/client/components/PuzzlePage.tsx, imports/client/components/Routes.tsx, imports/client/components/SetupPage.tsx, imports/client/components/Spectrum.tsx, imports/lib/models/call_participants.ts, imports/lib/models/call_signals.ts, imports/lib/models/facade.ts, imports/lib/roles.ts, imports/lib/schemas/call_participants.ts, imports/lib/schemas/call_signals.ts, imports/server/calls.ts, imports/server/setup.ts, server/main.ts
This change adds a WebRTC audio call to each puzzle.
Karen (@aldeka) provided mocks for the UI and then I went and yolo modified them; all credit for things looking good goes to her and all blame for anything that is ugly/broken goes to me. :)
There's several things I still want to do before submitting this, some of which may not be noted inline:
I still want to finish the following, but I think I'd probably be happy to punt them to followup PRs:
=> Add WebRTC calls on each puzzle page

imports/client/components/CallLinkBox.tsx, imports/client/components/CallSection.tsx, imports/client/components/ChatPeople.tsx, imports/client/components/SetupPage.tsx, imports/client/rtc_config.ts, imports/lib/models/facade.ts, imports/lib/schemas/settings.ts, imports/server/calls.ts, imports/server/setup.ts
This change shifts how RTC configuration is done, enabling us to use
authenticated TURN servers (which unlocks the ability to route traffic for
peers that cannot reach each other directly).
To accomplish this, the TURN server needs to be able to authenticate its
clients.  While there's a bunch of complicated ways to do this, there's also
one pleasantly simple approach in [1] that requires no more shared state than a
single shared secret between a web service (for us, the Meteor backend) and the
TURN server (for us, `coturn`).
We implement the token generation scheme with HMAC-SHA1 as specified, and
publish the resulting username/credential in a pseudocollection called
`rtcconfig`.  Since now TURN integration requires a secret, and since we're not
giving TURN config to non-authenticated …
=> Support TURN for peer discovery

client/stylesheets/puzzle.scss
Addresses the space formatting issue discussed in #291, using @zarvox's suggestion, but does not address the bigger questions raised by @ebroder.
With this change, emoji fonts are prioritized for blocks that people tend to describe as emoji (see below), after which we prefer monospace. For characters not available there, we fall back to the rest of the emoji fonts. My intent was to prefer monospace wherever it makes sense, conceding that it probably doesn't for clearly pictographic symbols.
The prioritized emoji include the self-evident 1F300-1FAFF, but also 2300-23FF (Miscellaneous Technical, which happens to include various timepiece symbols), 2600-26FF (Miscellaneous Symbols), 2700-27BF (Dingbats), and 1F100-1F1FF (Enclosed Alphanumeric Supplement, which includes the regional indicator …
=> Fix emoji spacing

imports/lib/models/base.ts
f66ec97c375f46717def29a5a4d653ff178540b8 fixed a bug in which I failed to add a
field to the schema, which caused the field to be dropped when serialized to
the database, which caused garbage collection of `CallParticipants` to do
nothing.
I expected `insert()` to reject types with fields that were not known to the
schema, but Typescript is generally permissive.
With this change, we reject arguments with unknown fields.  It catches the bug
fixed above via the typechecker.
=> Reject calls to `insert()` that have extra field not declared in schema

client/stylesheets/puzzle.scss, imports/client/components/Puzzle.tsx, imports/client/components/PuzzleAnswer.tsx, imports/client/components/Tag.tsx
General improvement of puzzle list presentation format and style.
- **All formats**
- Answers now display stacked one-per-line: _Improved visual inspection of all answers_
- Answers that wrap are indented: _Distinguishes wrapped answers at a glance_
- Change alignment to first baseline (Formerly vertically centered): _Visually aligns the two fonts used for title and answer (particularly noticeable in popover tables). In grid format, also places interface elements consistently in rows that wrap._
- Tags now break at colons: _Better wrapping_
- **Grid format** (as seen on the main puzzle list)
- Answers now wrap first at word-breaks, then by letter
- Move answers to a new line on narrow viewports: _Less text wrapping_
- Move edit button into its own flex item: _Title no longer wraps under …
=> Improve puzzle list presentation

client/stylesheets/puzzle.scss, imports/client/components/PuzzlePage.tsx, imports/client/components/TagList.tsx
We actually [discussed this in January](https://github.com/deathandmayhem/jolly-roger/pull/215#discussion_r248921246), but it might be worth revisiting in light of recent layout changes.
Removing the label frees up some space and generally makes the layout cleaner, in my opinion, and hopefully the purpose of tags is pretty self-evident even without the label. I added a "No tags yet" label, so the + button makes sense in that context.
When I put this together, I had forgotten that we already discussed this. @zarvox, please feel free to just cite the old discussion if your opinion hasn't changed.
=> Suggestion: Remove "Tags:" label from puzzle page

client/main.ts, client/stylesheets/_theme.scss, client/stylesheets/app.scss, client/stylesheets/breadcrumbs.scss, client/stylesheets/index.css, client/stylesheets/puzzle.scss, client/stylesheets/puzzlelist.scss
Previously, the global font stack was Helvetica Neue, Helvetica, Arial, while the answer font was simply system monospace. Both left a lot of room for inter-system variability, as many Linux systems will have none of those fonts installed, Helvetica Neue has significantly different metrics from Helvetica and Arial, and default monospace fonts vary significantly. As a result of incompatible metrics, this also led to layout variation, such as the vertical alignment issue noted by @zarvox in #367.
This standardizes on freely available fonts, ensuring consistent layout. It also drops bold styling of titles and answers in puzzle lists, which I believe was unnecessary and decreased legibility while taking up extra space.
The font chosen for answers had to meet the following requirements:
- …
=> Standardize fonts

client/stylesheets/puzzle.scss, client/stylesheets/puzzlelist.scss, imports/client/components/PuzzlePage.tsx
Previously, viewport width breakpoints were determined on a per-component basis. They're all close enough, however, that I think it makes more sense to have everything switch at common points and Bootstrap's default 576px sm breakpoint is a pretty good choice.
Dropped the old very small breakpoint responsible for hiding link text on phone-sized displays. With the viewers data moved elsewhere, there's plenty of space even on 320px wide viewports (and I don't think there's much to be gained by targeting devices narrower than that).
It's a deliberate choice not to use Bootstrap's `d-` classes in the couple of places where they could have worked in here. My preference is to keep that behavior together in the stylesheets (especially since we have a fair amount of more complicated breakpoint …
=> Use common breakpoints

imports/client/components/PuzzleModalForm.tsx
https://react-select.com/props explains a bit more about what arguments we get
passed here.  We should treat "no value" as "empty list", and otherwise update
the tags list in our state with whatever the callback says we have now.
Fixes #372.
=> Fix tag editor in puzzle creation modal

client/stylesheets/_theme.scss, client/stylesheets/app.scss, client/stylesheets/puzzle.scss
The "Platform Emoji" font-family was never getting used, because we were not
specifying valid `src` declarations for local fonts.  If a bare string is
provided, it is interpreted as a URL; we must specify `local()` to imply a
system-local font.
Once we started applying `local()` correctly, I found that we were missing the
ZWJ character needed to display the Jolly Roger pirate flag character: 🏴‍☠️
so I added it to the `unicode-range` for Platform Emoji.
Promoting "Platform Emoji" to lead the Bootstrap theme font families means that
we get reasonable emoji behavior throughout the app -- we'll use the platform
emoji fonts for those unicode ranges, and fall back to Source Sans Pro (or
Source Code Pro for monospace usages), and then try emoji fonts one more time
in case we missed the …
=> Fix emoji font usage

client/stylesheets/breadcrumbs.scss, client/stylesheets/puzzle.scss
Collection of minor fixes:
- Remove border around the iframe (bug introduced in bae327a)
- Fix a issue with the navbar breadcrumb padding in Safari
- Reduce navbar breadcrumb padding
=> Fix navbar breadcrumb padding and iframe border

client/stylesheets/puzzle.scss, imports/client/components/Documents.tsx, imports/client/components/PuzzlePage.tsx, imports/client/components/Tag.tsx, imports/client/components/TagEditor.tsx
Cleanup the puzzle metadata pane:
- Remove redundant title text and rearrange remaining content (see below)
- Move icons to the left of link text, for consistency
- Restore button height to the natural btn-sm styles and add an icon to the guess button, making them more obviously buttons. Previously, button height was reduced to fit them comfortably on the same row as text, but given the very flat theme and the similarly styled tags nearby, functionality was potentially ambiguous.
- Move verbose guess count text into a button badge
- Change answer background color to match the desaturated green used for solved puzzles elsewhere, both for consistency and to further distinguish answers from buttons
- Move the tag editor (the add tag interface) to its own line, avoiding the layout oddity of …
=> Puzzle metadata pane cleanup

imports/server/models/lock.ts, package-lock.json, package.json
Any time that an event fires that will resolve the future, we want to make sure to clear all other watches so it doesn't resolve multiple times.
I think this should fix the error that @zarvox reported:
```
I20210102-01:38:47.423(-8)? Exception in removedobserveChanges callback: Error: Future resolved more than once
I20210102-01:38:47.423(-8)?     at Future.return (/home/zarvox/.meteor/packages/meteor-tool/.1.12.0.4zjno.40411w++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:261:10)
I20210102-01:38:47.423(-8)?     at removed (imports/server/models/lock.ts:58:13)
I20210102-01:38:47.424(-8)?     at runWithEnvironment (packages/meteor.js:1286:24)
I20210102-01:38:47.424(-8)?     at packages/meteor.js:1299:14 …
```
=> Cleanup future handling in lock implementation

imports/server/discord-client-refresher.ts
I thought that `client.login` returned a promise that wasn't fulfilled until the
client was fully connected, but that doesn't seem to be the case. I observed
circumstances where the connection status was `IDLE` immediately after the
promise resolved, which would cause the connection management loop to exit
immediately, leaving nobody holding the gateway connection.
Instead use the ready event as a trigger.
@zarvox I think this fixes the issue you described where you could end up with no lock holder. (AIUI you also ended up with no gateway connection)
=> Block until fully connected to Discord

imports/client/components/HuntListPage.tsx, imports/client/discord.ts, imports/lib/active-operator-role.ts, imports/lib/roles.ts, imports/lib/schemas/hunts.ts, imports/lib/schemas/public_settings.ts, imports/server/discord.ts, imports/server/global-hooks.ts, imports/server/hooks/discord-hooks.ts, imports/server/models/lock.ts, imports/server/setup.ts
This adds:
* an optional object in Hunt for the id and name of a Discord channel
* a server-side publish to list Discord channels, guarded by
* a permission `discord.listChannels`, granted to operators
* UI to select the channel from a dropdown
* hook implementations to post a message to the channel when a puzzle
is added or solved, with a link to the Jolly Roger page for the puzzle
There's a couple other commits for some related code cleanups.
Example renderings:
=> Add Discord puzzle created/solved hooks

client/stylesheets/puzzle.scss, imports/client/components/CallSection.tsx, imports/client/components/ChatPeople.tsx
The call pane can take up a lot of space when many players are viewing a puzzle. As this space is better used for chat, give players the option to collapse the lists of viewers and callers. The default state is expanded caller list and collapsed viewer list.
My original intent was to collapse the two together, permitting even more space savings when fully collapsed, as caller and viewer counts could be displayed on a single line. However, the natural interface for this is the familiar collapsing hierarchy from the puzzle list page and it's a little odd to link collapses in that presentation. Additionally, perhaps the most natural state is to see callers but not passing-through viewers. The independent controls require an extra line in the fully collapsed state, but I think the tradeoff is …
=> Make viewer and caller lists collapsible

imports/client/components/AudioConfig.tsx, imports/client/components/ChatPeople.tsx
When a device is selected, we record its deviceId in localStorage,
and then retrieve it and specify it as the desired (but not required)
deviceId when calling `navigator.mediaDevices.getUserMedia()`.
Tested on Chrome on Linux by examining what device pavucontrol says
the stream is being captured from.
Fixes #356
=> Add audio input device selector to AudioConfig

imports/lib/active-operator-role.ts, imports/lib/models/discord_cache.ts, imports/lib/roles.ts, imports/lib/schemas/discord_cache.ts, imports/server/discord-client-refresher.ts
Set up a mongo cache that is updated whenever the Discord gateway client gets
notifications of object updates. In theory, we could use this to replace our own
API fetches of state.
=> Cache Discord API objects from the gateway

imports/lib/models/base.ts, imports/lib/models/call_participants.ts, imports/server/calls.ts, imports/server/migrations/30-index-call-participants.ts, imports/server/migrations/31-index-call-signals.ts, imports/server/migrations/all.ts
This patch series:
* Makes it possible to soft-delete multiple documents at once
* Adds indices for the various access patterns to `CallParticipants` and `CallSignals`.
* Swaps `CallParticipants.remove()` (hard-delete) to `CallParticipants.destroy()` (soft-delete) so we can collect some usage data during hunt and get a better picture of how the features get used (how many avg. concurrent users, largest mesh, call duration, do people disconnect/reconnect, etc.)
* Removes a stale unused ACL on CallParticipants; the server methods themselves implement all relevant logic.
=> Index call collections & soft-delete CallParticipants

client/stylesheets/debug.scss, imports/client/components/RTCDebugPage.tsx, imports/client/components/Routes.tsx, imports/server/admin-debug.ts, server/main.ts
This adds:
* an admin-only publish to dump *all* live `CallParticipants` and
`CallSignals` for all users
* a UI at `/rtcdebug` to give a heads-up view of what puzzles currently have
active calls and the current members of those calls, and
* a way to select a particular user who may be having connectivity issues, and
to see their `CallSignals` with each peer, which may help reveal where in the
WebRTC flow things have gone awry.
It's ugly but I expect to be ~the only person that looks at this.
=> Add RTC debug page

imports/client/components/ModalForm.tsx
See https://github.com/react-bootstrap/react-bootstrap/issues/5102
This (`animation={false}`) is the simple workaround for the react-bootstrap
issue linked above.  We could do some slightly more involved workarounds to
preserve the animation, but they'd break some abstractions (have to have a ref
of the child to focus, which limits the code's reusability) and honestly I find
the site feels slightly snappier without them.
So we just turn off `Modal` animations entirely.
Fixes #359.
=> Workaround react-bootstrap autoFocus bug by disabling animations

imports/client/components/NotificationCenter.tsx
Recall that in #184, users that we invited to Jolly Roger but who did not use their invite
code within Meteor's expiry time have to use password reset to be able to log
in for the first time.  When this happens, the password reset flow does not
perform our usual onboarding, which means that we have no display name or
phone number for that user, and indeed, no `Profile` object at all.  This is an
unfortunate state, and one that we'd like people to get out of promptly should it arise.
This adds another in-memory-dismissible notification that will be shown if the
user has no Profile object associated with their Meteor user id, which will
hopefully guide them to set a display name via the profile page.
(Also I snuck in a one-line fix for a bug -- the equivalent Discord nudge was missing the …
=> Nudge users missing a Profile object to set one

client/stylesheets/app.scss, client/stylesheets/puzzle.scss, client/stylesheets/puzzlelist.scss, imports/client/components/PuzzleListPage.tsx
- Multiline answer indents didn't render correctly in Safari, as ch does not size as expected with font fallback. Since we know the font, express in terms of em instead.
- Adjust puzzle group margin to align with header
- Fix inconsistent margins in puzzle list page controls
- Make puzzle list page control markup consistent
- Prefer standard to outline style buttons in radio and toggle bottoms, as the latter use the same colors for hover and active
- Use icon for clear button
=> Polish puzzle list page

imports/client/components/HuntListPage.tsx, imports/lib/schemas/hunts.ts, imports/server/chat.ts, imports/server/guesses.ts
Somewhat annoyingly, you can spoof username with a webhook, but not with a bot channel post, so I'm using the embed formatting. It's not perfect, but it's probably good enough.
=> Add support for Discord firehose

imports/server/chat.ts, imports/server/guesses.ts, imports/server/hooks/discord-hooks.ts, imports/server/hooks/hooks-registry.ts, imports/server/hooks/hookset.ts
Pluggable actions to take with optional integrations when a chat message is
created seems like exactly the sort of use case the hook system was designed
to support.
Shifting the code there made it easy to notice and fix a couple of bugs along the way:
* The firehose did not respect the `disable.discord` flag.
* System ChatMessages created in response to guesses transitioning states were
double-created.
=> Extract Discord firehose chat behavior to a hook

imports/client/components/NotificationCenter.tsx, imports/lib/models/base.ts, imports/server/guesses.ts
Historically, in order to display pending guesses, the operator view has loaded all hunts and puzzles. If a Jolly Roger instance has a lot of history, that can be quite expensive. Instead, expose a special subscription that includes pending guesses + the specific hunts/puzzles that they're linked to. This requires more state tracking on the server, but since there are relatively few operators it seems worth that cost.
(FWIW, this could be made even more efficient if we projected puzzles and hunts for just the fields that we care about, but that creates some risk to type safety that I don't really want to touch. It's also possible we could generalize some of this logic for other use cases, e.g. pending announcements + announcements, although we couldn't lean on the assumption that it will …
=> Make initial page load faster for operators

imports/server/guesses.ts
This will help make it more visible when someone submits a new guess,
so you don't get multiple people submitting the same guess as often.
Most users aren't operators, so the only hint that someone else has
submitted a guess is the number on the `Guesses (1)` button changing,
which isn't super noticeable.
Fixes #290.
=> Synthesize new guess submissions in puzzle chat

imports/client/components/GuessQueuePage.tsx, imports/client/components/ProfileList.tsx, imports/client/components/TagList.tsx
Update button styles elsewhere to match #405, in which outline classes are used exclusively for toggle and radio buttons.
(While the buttons in voice chat are toggle-like, they also change their own text and color and behave more like swapping buttons than toggles. They are unchanged here.)
=> Button consistency

imports/client/components/Tag.tsx
Previously, on devices that do not support hover, clicking into an iframe did not dismiss the popover. Per @zarvox's suggestion, solve this by adding a blur event handler to the window. This has the side effect of closing popovers when switching tabs (on mobile - elsewhere they were already closed by mouseLeave).
This fix requires switching from focus to click as the secondary trigger. As a result, clicking the tag can also close the popover (on any platform), which seems reasonable.
Closes #377
=> Close popover when clicking into iframe

imports/client/components/OthersProfilePage.tsx
I've wanted to be able to look this up a couple times. It's not perfect (since it doesn't show a custom nick if you've set one on our server), but still seems useful.
I would entertain an argument that this should only be shown to operators or something, but given that everyone's already in the guild, it doesn't feel like the mapping here is super secret information.
=> Display Discord handle on the profile page

imports/client/components/NotificationCenter.tsx, imports/client/components/OwnProfilePage.tsx, imports/client/components/ProfilePage.tsx, imports/client/components/SetupPage.tsx, imports/lib/models/chat_notifications.ts, imports/lib/models/facade.ts, imports/lib/schemas/chat_notifications.ts, imports/lib/schemas/facade.ts, imports/lib/schemas/profiles.ts, imports/server/chat-notifications.ts, imports/server/global-hooks.ts, imports/server/guesses.ts, imports/server/hooks/dingword-hooks.ts, imports/server/migrations/32-index-chat-notifications.ts, imports/server/migrations/33-index-profile-dingwords.ts, imports/server/migrations/all.ts, imports/server/profile.ts, imports/server/refcounted-observer-map.ts, server/main.ts
The simplest thing that could work, labeled as experimental, and guarded by a feature flag in the event the naive approach turns out to generate way too much server load.
We add:
* a Profile field `dingwords`, with a list of strings
* a way to edit it in OwnProfilePage
* a circuit breaker `disable.dingwords` on the setup page
* a `DingwordHookset` to, for each chat message sent, check if any users want to get notified, and generate notifications accordingly
* a reactive smart subscription `chatNotifications` which ensures that the puzzle and hunt are available clientside if a chat notification references them
* a new NotificationCenter notification type which links to the puzzle, and shows the sender and the message, and allows the notification to be dismissed
No desktop notifications …
=> Add experimental dingwords and in-app notifications

.meteor/packages, .meteor/release
Per https://forums.meteor.com/t/new-meteor-release-2-1/55324 it's just
taking a node security release.
=> Update to Meteor 2.1

client/stylesheets/puzzle.scss, imports/client/components/RelatedPuzzleList.tsx, imports/client/components/Tag.tsx
Adds a button to copy related puzzles and answers to clipboard.
Format is tab delimited for pasting into spreadsheets. Each answer has its own line (with puzzle name repeated). If fewer answers are present than expected, rows with blank answers are appended. Exports at least 1 line even for puzzles with 0 expected answers (which is currently not allowed).
=> Add copy-to-clipboard button to related puzzles

client/stylesheets/puzzlelist.scss, imports/client/components/PuzzleListPage.tsx
Makes it easy to get a sense of overall hunt progress at a glance.
Text vertically aligns with the "View puzzles by:" label and the search box and is a label for the search box:
Updates to reflect the number of matched items:
Counts by puzzles, not by rows shown, since some puzzles may appear multiple times:
=> PuzzleListPage: show number of items visible/total

imports/client/components/PuzzleListPage.tsx
And use that value as the default value on PuzzleListPage for that Hunt.
This has the effect of making the toggle "sticky", which makes the "hide
solved" view more useful, especially later on in hunts when there are
many solved puzzles and we're trying to see the ones that remain more
clearly.
Now that we have UI that indicates that we're hiding some subset of
puzzles when applying either a search or an unsolved filter, I'm less
concerned about folks accidentally hiding solved puzzles and being
confused when they can't find the puzzle they're looking for, so I'm
more comfortable with the idea of hiding solved puzzles more of the
time.
Fixes #423.
=> Save last "Show solved" state per Hunt in localStorage

imports/client/components/App.tsx
I strongly suspect no one has ever actually clicked this link, but just
in case, since we're running this as an open project, it makes more
sense for the link to point to our public issues tracker than our old
internal mailinglist, and changing the link is ~a free action.
(There's a couple other places we still ref dfa-web@ in email templates; I'm punting on that for now since I'm imagining that as part of a more holistic "branding/whitelabeling" workstream ala #193.)
=> Make "report an issue" link point to GitHub issues

imports/client/components/SetupPage.tsx, imports/lib/roles.ts, imports/lib/schemas/settings.ts, imports/server/accounts.ts, imports/server/hunts.ts, imports/server/setup.ts
This change:
* adds a new Setting type for email configuration which covers all the
deployment-specific configuration that was previously hardcoded in the
jolly-roger source
* adds a Meteor method in setup.ts to save this configuration to the DB
* adds UI in SetupPage to edit the From: address and email templates,
along with an explanation of what variables are available at
email-rendering time, and to call the method to save the config values
* adds code in imports/server/accounts.ts to monitor that setting for changes and update
`Accounts.emailTemplates` accordingly when changes are observed, so that the Meteor
accounts system will use the templates and `From:` as desired.
* adds code to render Mustache templates to produce email contents when
we want to send email
Related to #193.
Once …
=> Make email configurable via a new Setting with templates

package-lock.json, package.json
This was a holdover from the olden days when we still used
`React.createClass` rather than ES6 classes.  It's no longer
referenced, so we can drop it from our deps.
=> Remove unused `react-addons-pure-render-mixin` dep

imports/client/components/AccountForm.tsx
There's two sites we call the `saveProfile` Meteor method; the one in
the enrollment flow was broken because we did not include a `dingwords`
parameter, which the server checks.
=> Fix bug where saving profile during onboarding was broken by missing dingwords

.meteor/packages, client/stylesheets/loading.scss, imports/client/components/Loading.tsx, imports/client/components/Routes.tsx
This is made pretty straightforward with the introduction of React.lazy and the Suspense component. The only thing we really need to provide is a placeholder component to use as a loading indicator.
This doesn't seem to make much of a dent in the bundle size, likely because most of the bundle is dependencies, and I don't think removing these pages allows for pruning many dependencies, but it still seems like good hygiene and a good leaping off point for more code splitting later.
Here's what the loading component looks like for reference:
For what it's worth, I'm somewhat tempted to switch some of the "loading..." text placeholders to use the spinner instead, since I think the UI is a little cleaner. I'll probably play with it some and see if it works.
I'm going to say this fixes #111, …
=> Add async loading for SetupPage and RTCDebugPage

client/stylesheets/loading.scss, client/stylesheets/puzzle.scss, imports/client/components/Loading.tsx, imports/client/components/Puzzle.tsx, imports/client/components/PuzzleModalForm.tsx, imports/client/components/TagEditor.tsx, imports/client/components/TagList.tsx
The puzzle edit modal and the tag editor are the only 2 places where we use react-select, which is an otherwise fairly expensive require (about 60K in the final bundle). By pushing the react-select usages to use dynamic-import we can slim down the default fetch.
I tested this using the Chrome dev tools with a custom throttling profile that added 2 seconds of latency.
Here's what the tag selector looks like:
And here's what the puzzle edit modal looks like:
=> Make react-select dynamically imported

client/main.ts, imports/client/components/AnnouncementsPage.tsx, imports/client/components/HuntApp.tsx, imports/client/components/HuntProfileListPage.tsx, imports/client/components/NotificationCenter.tsx, imports/client/components/PuzzlePage.tsx, imports/client/markdown.ts, imports/lib/models/meteor_users.ts, imports/model-helpers.ts, imports/server/accounts.ts, imports/server/announcements.ts, imports/server/api/resources/users.ts, imports/server/guesses.ts, imports/server/hooks/dingword-hooks.ts, imports/server/hunts.ts, imports/server/migrations/7-more-indexes.ts, imports/server/profile.ts, imports/server/puzzle.ts, imports/server/setup.ts, imports/server/users.ts, server/main.ts
This trims down the set of things that we import in `client/main.ts`, in favor of pulling things in as they're actually used. This makes it potentially more feasible to trim out unused dependencies in the future.
I think the dependency pruning of the `loadFacades` change is worth it, since it's only used by admins doing sketchy things in the console, but I'm open to pushback. (Note that `await loadFacades()` will do the right thing and block until `Models` and `Schemas` are populated)
=> Cleanup main imports

imports/client/components/AnnouncementsPage.tsx, imports/client/components/AuthenticatedRoute.tsx, imports/client/components/HuntApp.tsx, imports/client/components/HuntListPage.tsx, imports/client/components/HuntProfileListPage.tsx, imports/client/components/RelatedPuzzleGroup.tsx, imports/client/components/SplitPanePlus.tsx, imports/client/components/TagList.tsx, imports/client/components/UnauthenticatedRoute.tsx, imports/lib/models/base.ts, imports/lib/schemas/typedSchemas.ts, imports/lib/schemas/users.ts, imports/model-helpers.ts, imports/server/blanche.ts, imports/server/hunts.ts, imports/server/profile.ts, imports/server/puzzle.ts, imports/server/users.ts, types/user.d.ts
Three main types of changes here:
* Removing the underscore import from files where it wasn't used at all. Typescript makes it an error to have unused variables, but I think it misses this because it starts with (is) an underscore.
* Replacing underscore with native equivalents. I think in the early days of working on jolly-roger, I used underscore more heavily because I assumed that it new something about, like, weird Javascript prototypical inheritance that I didn't, but in practice there's really no reason to use `_.map` or `_.filter`.
* Replacing underscore where it obfuscates typing information. The type annotations on underscore are mostly pretty good, but a few of them are quite bad - `_.extend` and `_.omit` in particular have a tendency to just return `any`. Plus the spread …
=> Remove some unnecessary uses of underscore

package-lock.json
This required some dependency spelunking, but upgrading cheerio (a
direct dependency of enzyme) using `meteor npm update cheerio --depth 2`
picked up the requisite update. Since enzyme is only used as part of the
test suite and the browser-simulation tests still pass, this should be
low risk.
=> Take updates for CVE-2021-3803

README.md
Slightly better discoverability. (To prevent this from being abused, I also set the server to disallow new members from posting until they've been a member for 10 minutes, which hopefully gives us a little opportunity to moderate. If we see someone known-trusted, we can tag them with a role which will bypass. If all of this turns out to be a terrible idea, we can also nuke the invite link)
=> Add a link to Discord server

.eslintrc.json, imports/client/components/PuzzlePage.tsx, imports/client/components/SetupPage.tsx
Some of our eslint config dated from before we switched to using
functional components and are no longer problematic. Re-enabling
`react/no-unused-prop-types` didn't seem to flag any false-positives,
but did find some props in SetupPage that weren't being used.
This also enables exhaustive dep checks for `useTracker`, which aren't
enabled by default. This found one false-positive in PuzzlePage which
was easily addressed by restructuring the variable usage. My general
philosophy is that it's worth working around slightly overzealous
linters, so long as it's not hard to do so (I don't think it is in this
case), if those linters would catch real bugs (I think this one would).
=> Lint fixups

imports/server/discord-client-refresher.ts, imports/server/onExit.ts
Meteor doesn't set signal handlers by default, so when we set a signal
handler, we were in fact, bypassing the default handling of the signal
(i.e. exiting). Add a helper which runs signal handlers, cleans up after
itself, and then re-signals to actually cause the process to exit.
=> Clean up shutdown process

imports/client/components/HuntListPage.tsx, imports/client/components/SetupPage.tsx, imports/server/setup.ts
There are a couple of scattered bugs here which mostly come down to
Meteor's check function being strict about object keys and Typescript
being loose. In Meteor, it's an error to pass keys in an object that
aren't part of the checked shape. In Typescript, this is allowed (the
keys just aren't accessible).
We were silently ferrying around all of the keys from the Discord cache
record, which caused an error at check time. Instead, pick off the
specific keys we care about.
(Also fix a small typo in the setup page server logic)
Fixes #470.
=> Fix Discord object selection

imports/server/models/lock.ts
The logic in aa05df90 for lock preemption was backwards (because the
logic is backwards relative to everywhere else we catch a duplicate key
error). This caused us to throw the duplicate key error (and in the
event of any other error, we'd try to preempt the lock 😬)
=> Fix lock preemption

imports/server/hooks/discord-hooks.ts
It is apparently an error to submit an embedded fields record with the
empty string as its value.
Fixes #473.
=> Fix Discord error when creating untagged puzzle

cloudformation/jolly-roger.yaml
On the smallest instances that Jolly Roger runs on (t3a.nano-ish), we're
very memory-constrained. SSM and snapd both use valuable memory, which
in turn causes swap thrashing. Uninstalling both seems to be enough to
save us.
=> Uninstall Amazon SSM and snapd to save memory

cloudformation/jolly-roger.yaml
This disables the tracing, dogstatsd, and security agents, none of which we use. It's still a memory hog, but this seems to make it better.
I'm undecided if this is actually a good idea or not, but we are pretty memory constrained on t3a.nano and we're about to add the Mediasoup logic.
Note that the shenanigans around the security agent are related to what seems to be a bug. This logic seems designed to cause the security agent to quit if it isn't enabled:
https://github.com/DataDog/datadog-agent/blob/f4cbdd633850263e8aab363c008087ab8b2ed72d/cmd/security-agent/app/app.go#L211-L219
But if that function returns `nil`, then the main function just blocks until it gets a signal on stopCh (which fires on Unix signal):
https://github.com/DataDog/datadog-agent/blob/f4cbdd633850263e8aab363c008087ab …
=> Slim down dd-agent's footprint

cloudformation/jolly-roger.yaml
I'm not wild about CloudWatch in general as a service, and this does
theoretically cost us some metrics that the Datadog agent is capable of
capturing, but we don't make that much use of those metrics today, and
the CloudWatch agent uses significantly less memory than Datadog.
=> Switch to using CloudWatch agent for host metrics

Dockerfile, cloudformation/jolly-roger.yaml
Now that we're running RTC traffic directly through the jolly-roger
container, we should move it to host networking to save on overhead. The
easiest way to make this work was to just switch to the standard nginx
container and provide our own nginx config (which is mostly taken from
the config that nginx-proxy was previously rendering).
(Running in production successfully already)
=> Switch to host networking in CloudFormation config

.babelrc, .meteor/packages, .meteor/versions, package-lock.json, package.json
Switching from Meteor's standard minifier to the zodern packages emits
sourcemaps. The add-react-displayname Babel plugin adds a `displayName`
property to React components, which causes them to show up with
unmangled names in the React dev tools (which apparently can't use
sourcemaps to pierce the minification on its own).
Neither of these are perfect - in particular, some of the libraries we
include seem to not get included in sourcemaps or have their display
names tagged correctly - but I think this is still a meaningful
improvement.
=> Make debugging in prod slightly more pleasant

imports/client/components/CallSection.tsx
These logs are specifically intended for telling if we're churning
objects unnecessarily (potentially an indication of WebRTC
characteristics).
=> Add some more logging to CallSection

.meteor/packages, .meteor/release, .meteor/versions
Update log:
```
zarvox@minotaur jolly-roger % meteor update
Changes to your project's package version selections from updating the release:
babel-compiler          upgraded from 7.7.0 to 7.8.0
ecmascript              upgraded from 0.16.0 to 0.16.1
hot-module-replacement  upgraded from 0.4.0 to 0.5.0
modules                 upgraded from 0.17.0 to 0.18.0
react-fast-refresh      upgraded from 0.2.0 to 0.2.1
typescript              upgraded from 4.4.0 to 4.4.1
jolly-roger: updated to Meteor 2.5.2.
Changes to your project's package version selections from updating package versions:
meteortesting:browser-tests  upgraded from 1.3.4 to 1.3.5
react-fast-refresh           upgraded from 0.2.1 to 0.2.2
The following top-level dependencies were not updated to the very latest version available:
* http …
```
=> Update Meteor to 2.5.2

imports/client/components/AccountForm.tsx
Fixes #455.
Actually #455 was mostly already fixed in
3a678503dda80c5d7f18db16db4d4c63fde11f25, but these TODOs were still
hanging around.  We can close them out now though.
=> Use <Button variant="link"> instead of <a href="#">

imports/client/components/ProfileList.tsx
This makes the two profile list pages slightly more usable by including
recognizable avatars (when present) and also allowing the filter-search
to search over the user's linked Discord handle and disambiguator. This
should help make it easier to identify the jolly-roger user associated
with a Discord user if their Discord profile and handle lack useful
identifying information.
Before:
After:
=> Show Discord avatars in ProfileList and search over Discord handle/disambiguator

imports/server/mediasoup-api.ts, imports/server/mediasoup.ts
We listen for all peers being deleted because that's our best
opportunity to clean up any cached RTP parameters we have for that peer,
but because it runs on all servers, we don't want each of them to emit a
log line telling us that a new peer joined.
=> Clean up peer join logging

cloudformation/jolly-roger.yaml
This makes it possible to ping deathandmayhem.com directly.
=> Enable ICMP echo request/reply and frag needed on ALB

imports/client/components/Puzzle.tsx, imports/client/components/PuzzleListPage.tsx, imports/client/components/PuzzleModalForm.tsx, imports/client/components/PuzzlePage.tsx
For puzzles where expected answer count is exactly zero:
* On the puzzle page, don't show the answer submission/guess queue
submission button or modal
* On the puzzle list page, consider the item eligible to be shown
alongside unsolved puzzles, since these are usually pinned
administrivia that we don't want to disappear.
* On the puzzle list page, don't show viewer counts
* On the puzzle list page, style the puzzle row in light purple (as we
currently do for administrivia)
We retain the sort order behavior of the `administrivia` tag (sorts
above all other groups).
I audited the remaining references to the string `administrivia` as well
as the `expectedAnswerCount` field; they all look good.
Fixes #512.
=> Allow `expectedAnswerCount` to be zero

imports/client/components/App.tsx
Upgrading Bootstrap caused a bug because they began floating the
separator. This works if you're using display: flex, but we were
overriding with display: block to get better wrapping behavior. But
given that we were overriding Bootstrap's styling so heavily, we weren't
getting any benefit from using the Bootstrap classes in the first place,
so just switch to our own version.
Verified that this seems to do the right thing at small window sizes on Chrome, Firefox, and Safari.
=> Use our own breadcrumb implementation

imports/client/components/CallSection.tsx, imports/client/components/ChatPeople.tsx, imports/client/components/PuzzlePage.tsx, imports/client/components/SplitPanePlus.tsx
Most of the time, users are interested in the most recent chunk of chat
history, and think of the backlog as being pinned to the bottom, rather
than the top.  However, in the web APIs, overflow definitely defaults to
considering space from the top-left corner of a rectangle.
To approximate the "fixed distance from bottom of scrollback" behavior,
we save the distance from the bottom that we're aiming for, and have a
function which jumps to the appropriate scrollTop value to maintain that
distance-from-bottom which we call in response to a number of possible
ways that might cause the space available to the chat history pane (or
the space demanded by the contents to be displayed) to change:
* Callers or viewers are collapsed or expanded
* New callers or viewers join or leave, causing their …
=> Rework chat scroll position behavior

.github/dependabot.yml
We currently get security updates from dependabot automatically. This will additionally start opening PRs for non-security updates to dependencies, which hopefully will reduce the frequency with which I have to do this myself.
(And given our acceptance tests, we have some bare minimum confirmation that the site doesn't totally fail to load)
=> Enable dependabot non-security updates

Dockerfile, tests/acceptance/authentication.tsx, tests/acceptance/lib.ts
Fetch meteor packages when we handle dependencies. This enables better caching across builds and eliminates some duplicated time spent between the parallel test and build phases.
Add some additional logging. We've seen intermittent test timeouts in the acceptance test setup phase (deleting the database, creating a test user, logging in as that test user). I haven't been able to reproduce it on demand, but hopefully this will give us better information about where the timeouts are occurring.
(I originally opened this PR to try and reproduce some test flakiness we saw after re-enabling the test suite, but I haven't been able to reproduce, so I'm settling for small test improvements to improve our chance of catching it next time)
=> Small test improvements

imports/client/components/FirehosePage.tsx, imports/client/components/HuntApp.tsx, imports/client/components/PuzzleListPage.tsx
This page adds an in-app view of the sort that we historically aimed for
from the firehose in IRC, Slack, or Discord, where we could see all chat
messages on all puzzles in a single interleaved time-series view.
I'm ignoring formatting here for now; this is largely to make searching
over the whole of a hunt's chatlogs easier.
The filter search only looks at the message text; if you wanted to
filter on a single puzzle, just go view the log from the puzzle page.
=> Add FirehosePage for tailing/searching all chat messages

imports/client/components/App.tsx
Suggested fix for iOS navbar overscrolling issue. Switches navbar back to fixed from sticky.
Closes #543.
=> Prevent navbar overscroll on iOS

client/stylesheets/puzzle.scss, imports/client/components/Puzzle.tsx, imports/client/components/PuzzleAnswer.tsx, imports/client/components/PuzzleList.tsx, imports/client/components/RelatedPuzzleList.tsx, imports/client/components/Tag.tsx
Adds a convenience feature which standardizes spacing in related puzzle answers for spotting patterns. A toggle on the related puzzle popover switches between preserving original spacing and removing all spaces (displayed segmented into groups of five characters for easy indexing). The copy button is aware of the spacing setting and copies answers to the clipboard without spaces as appropriate. (Whether using the copy button or highlighting and copying, the gaps between segments are for display only and do not add space characters in the copied text.)
Historically, hunters and operators have been inconsistent about spaces in answers. Hopefully, display flexibility will encourage us to standardize on preserving natural spaces.
Respace off:
Respace on:
=> Spacing options for PuzzleAnswer

imports/client/components/AccountForm.tsx, imports/client/components/AllProfileListPage.tsx, imports/client/components/AnnouncementsPage.tsx, imports/client/components/App.tsx, imports/client/components/CelebrationCenter.tsx, imports/client/components/ChatPeople.tsx, imports/client/components/FirehosePage.tsx, imports/client/components/GuessQueuePage.tsx, imports/client/components/HuntApp.tsx, imports/client/components/HuntListPage.tsx, imports/client/components/HuntProfileListPage.tsx, imports/client/components/LabelledRadioGroup.tsx, imports/client/components/NotificationCenter.tsx, imports/client/components/OwnProfilePage.tsx, imports/client/components/ProfilePage.tsx, imports/client/components/PuzzleListPage.tsx, imports/client/components/PuzzlePage.tsx, imports/client/components/RTCDebugPage.tsx, imports/client/components/RootRedirector.tsx, imports/client/components/SetupPage.tsx, imports/client/components/SplashPage.tsx, imports/client/components/SubscriberCount.tsx, imports/client/components/TagEditor.tsx, imports/client/components/UserInvitePage.tsx, imports/client/hooks/use-subscribe-avatars.ts, imports/client/hooks/use-subscribe-display-names.ts, imports/lib/models/profiles.ts
This makes a handful of updates to how we use Meteor's React hooks in a way that I think is generally better, although it's certainly debatable the extent to which these are objective improvements vs. my own personal sense of hygiene. The diff is churn-y, but relatively rote, and should be reviewable commit-by-commit against the specific goal of that commit. My high-level goals were:
* Use [`useSubscribe`](https://github.com/meteor/react-packages/tree/master/packages/react-meteor-data#usesubscribesubname-args-a-convenient-wrapper-for-subscriptions) for everything. IMO its behavior is much cleaner than having `Meteor.subscribe` calls inside of `useTracker`, and my experiences using it for the new WebRTC code were quite positive. In the past, I observed that when a `useTracker` re-runs its …
=> Tracker updates

client/stylesheets/puzzle.scss, imports/client/components/App.tsx, imports/client/components/PuzzleListPage.tsx, imports/client/components/styling/FixedLayout.tsx, imports/server/server-render.ts, imports/server/site-manifest.ts
Adds basic PWA support, so the app can be used without browser UI. To take full advantage of this, switch viewport-fit to cover and enforce inset environmental variables.
- Support standalone functionality without browser UI ("Web Clip" on iOS)
- Accommodate bottom inset (home indicator on iOS devices) to avoid blocking content. Scrolling layouts scroll under it, but with bottom padding to clear it when scrolled to the bottom. Fixed layouts keep out entirely. Notably, the home indicator no longer overlaps Google Sheets tab navigation on PuzzlePage.
- The navigation bar is now always full screen width, but its content is padded to respect insets. (Somewhat out of scope: also addressed padding the user dropdown away from the edge.)
- On windows with horizontal insetting (like an iPhone in …
=> Progressive Web App support

package-lock.json
I was hoping dependabot would figure out how to do this on its own but I guess not. (Generated with `meteor npm audit fix && meteor npm i`)
=> Pick up node-forge security update

.gitignore, .vscode/extensions.json, .vscode/settings.json
These files were originally gitignored, but are an easy way to improve
the onboarding process by encouraging VS Code to match our style guide.
=> Add recommended configuration for VS Code

imports/client/components/ChatPeople.tsx, imports/client/components/RTCDebugPage.tsx, imports/lib/config/webrtc.ts, imports/lib/models/facade.ts, imports/lib/models/mediasoup/call_histories.ts, imports/lib/relativeTimeFormat.ts, imports/lib/schemas/facade.ts, imports/lib/schemas/mediasoup/call_history.ts, imports/lib/schemas/mediasoup/room.ts, imports/lib/schemas/mediasoup/router.ts, imports/server/mediasoup-api.ts, imports/server/mediasoup.ts, imports/server/migrations/36-call-history-indexes.ts, imports/server/migrations/all.ts, tests/main.ts, tests/unit/imports/lib/relativeTimeFormat.ts
Use AudioLevelObserver + some debouncing to keep track of the last time
there was voice activity (with roughly 60 second granularity), and keep
that on a new CallHistories model (which persists across calls being
started/stopped, unlike any of the other Mediasoup models).
This data gets displayed in the call section if you're not currently
joined to a call.
Here are some examples of what that might look like:
(Note that we'll only ever see "seconds ago" in development mode. Adding the activity note to the puzzle list page is left as an exercise for future-me assuming we're happy with the rest of this.)
=> Track recent activity in voice chat

client/stylesheets/puzzle.scss, imports/client/components/CallSection.tsx, imports/client/components/ChatPeople.tsx, imports/client/components/PuzzlePage.tsx, imports/client/components/styling/FixedLayout.tsx, imports/lib/discord.ts
- Move chat controls and call interface away from edges. The nonstandard controls are more trouble than they're worth. Adding padding makes buttons more clear, improves the focus effect, looks more natural when a bottom inset is present, and reduces amount of non-standard styling.
- Extend the fixed layout to the bottom, when bottom inset is non-zero. Resizer makes more sense stretched to full height and chat input needn't waste vertical padding. This is a first step in better using the areas outside the inset.
- Style improvements for people in chatter
- Add gap between. Remove disused connection status bar.
- Remove inconsistently visible background shading on deafen.
- Fix mute and deafen icon overflow.
- Get higher resolution discord icons (for hiDPI displays).
- Capitalize voice chat …
=> PuzzlePage interface style polish

imports/client/components/App.tsx, package-lock.json, package.json
This gives us a slightly better UX than having the entire app unmount
and leave the user with a blank screen. The "reset" button is admittedly
not likely to solve anyone's problems, but it at least gives them some
agency and an opportunity to go somewhere else
Here's an example of what it looks like:
I was hoping to include the stack from Mobile Firefox, but sadly I don't seem to be able to repro on my local dev environment.
.
=> Add an error boundary to the main App component

imports/client/components/App.tsx, package-lock.json, package.json
This is a little frivolous, but probably worth merging. In particular, this gives us some indirection around differences in browser behavior. Chrome includes the exception message in `Error.stack`; Firefox does not. I also thought Firefox's stacktraces were kind of ugly, but that's really just because of the minification in prod. This doesn't do anything about minification yet, because `stacktrace-gps` only supports the `//# sourceMappingURL` magic comments and not the `X-SourceMap` header that Meteor uses.
Before:
After:
(The rendering on Chrome is about the same before and after)
=> Run errors through StackTrace.JS before rendering them

client/main.ts, imports/client/components/CallSection.tsx, imports/client/components/ChatPeople.tsx, imports/client/components/PuzzlePage.tsx, imports/client/tracing.ts
My primary goal here was to have something I could turn on for myself at
runtime from a JS console in production without causing notable
performance degradation or increased memory usage for anyone else.
This has the potential to cause nontrivial memory usage when tracing is
enabled, as I didn't bother dropping traces or capping the trace buffer
size or anything.  I recommend leaving it off unless you're actively
debugging an issue in prod that you're unable to reproduce locally,
which is unfortunately where I am right now with the sidebar scrolling
on page load.
To enable tracing on initial page load, run
`localStorage.setItem("tracingEnabled", 1)` from the browser JS console.
To disable tracing on page load, run
`localStorage.removeItem("tracingEnabled")` from the browser JS console. …
=> Add some prod-enableable client-side tracing to debug scroll position issue

imports/client/components/ChatPeople.tsx, imports/client/components/Puzzle.tsx, imports/client/components/PuzzleDeleteModal.tsx, imports/client/components/PuzzleListPage.tsx, imports/client/components/PuzzlePage.tsx, imports/lib/schemas/puzzle.ts, imports/server/gdrive.ts, imports/server/puzzle.ts
Operators are now allowed to delete puzzles. When they do, they can
optionally specify another puzzle that hunters should treat as its
replacement. When a puzzle is deleted, chat and guesses are disabled,
all edit permissions are revoked from the shared Google document, and a
modal pops up advising hunters that the puzzle is deleted and now
read-only.
Deleted puzzles show up in the operators' puzzle list view at the very
bottom in an independent group, and the modal on the individual puzzle
page has a "undelete" button in case of error.
Fixes #425.
Here are some screenshots
=> Add a puzzle delete button

imports/client/components/HuntProfileListPage.tsx, imports/client/components/NotificationCenter.tsx, imports/client/components/OthersProfilePage.tsx, imports/client/components/OwnProfilePage.tsx, imports/client/components/ProfileList.tsx, imports/client/components/ProfilePage.tsx, imports/client/components/Puzzle.tsx, imports/client/components/PuzzleListPage.tsx, imports/client/components/RTCDebugPage.tsx, imports/client/components/SetupPage.tsx, imports/client/hooks/persisted-state.ts, imports/lib/is-admin.ts, imports/lib/models/base.ts, imports/lib/models/settings.ts, imports/lib/permission_stubs.ts, imports/lib/schemas/user.ts, imports/server/api/resources/users.ts, imports/server/api_keys.ts, imports/server/guesses.ts, imports/server/hunts.ts, imports/server/migrations/37-role-reorganization.ts, imports/server/migrations/all.ts, imports/server/models/api_keys.ts, imports/server/operator.ts, imports/server/setup.ts, imports/server/users.ts, package-lock.json, package.json, types/user.d.ts
Implements the design in #618.
Fixes #212, #599, #618.
Biggest UI change is to the profile list page:
The page also supports searching by role (if you have access to role data, which requires you be an operator/admin):
There's also a new button on the puzzle list page to toggle operator UI status:
This doesn't address #230, which can make toggling the operator UI potentially difficult, but it does peek out just enough that you can grab it.x
=> Per-hunt permissions

imports/client/components/Puzzle.tsx
(Fixes a bug where toggling operator mode and putting any value into
localStorage would hide operator mode permanently.)
=> Use hunt-scoped localStorage in puzzle list entry

imports/lib/models/base.ts, imports/lib/models/folder_permissions.ts, imports/lib/models/mediasoup/call_histories.ts, imports/lib/models/pending_announcements.ts, imports/model-helpers.ts, imports/server/models/api_keys.ts
Previously, for publishing data, when the client sent us a query filter,
we would mutate it in order to add a constraint on (e.g.) hunt
membership. However, we can instead use Mongo's built in $and operator
to specify a separate query term that documents must satisfy. This is
much more straightforward and less error prone.
(I also specifically verified that Mongo's query planner is able to
handle this case - if, e.g., you have one $and branch that specifies
hunt: $in, and another that specifies hunt: $eq, it will merge those and
create a single set of index bounds on the $eq value.)
Fixes #604.
(It's also worth noting that Meteor's docs [specifically recommend](https://guide.meteor.com/security.html#:~:text=raise%20performance%20issues.-,Passing%20in%20a%20filter,-%3A%20If%20you%20want) …
=> Use $and for query constraints instead of mutation

client/stylesheets/puzzle.scss, imports/client/components/AudioConfig.tsx, imports/client/components/CallSection.tsx, imports/client/components/ChatPeople.tsx, imports/client/components/Documents.tsx, imports/client/components/LabelledRadioGroup.tsx, imports/client/components/PuzzlePage.tsx, imports/client/components/styling/DiscordAvatarImg.tsx, imports/client/components/styling/PeopleComponents.tsx, imports/client/components/styling/constants.tsx
This covers the rest of the chat + call participants sections, leaving
pretty much just the `SplitPanePlus`-related styles defined in
`puzzle.scss`.
This change should have no visible differences.
=> Convert more styles from scss to styled-components

imports/client/components/AllProfileListPage.tsx, imports/client/components/HuntProfileListPage.tsx, imports/client/components/OthersProfilePage.tsx, imports/client/components/ProfilePage.tsx
Don't show profiles for users with no profile, and don't always load
your own profile when viewing anyone's profile page.
There's still one outstanding bug which is that the `avatars` subscription doesn't seem to actually return any data. I haven't been able to figure out why, but these are bad enough that we should go ahead and land fixes while I investigate.
=> Profile list/page fixes

imports/client/components/AllProfileListPage.tsx, imports/client/components/App.tsx, imports/client/components/CallSection.tsx, imports/client/components/CelebrationCenter.tsx, imports/client/components/ChatPeople.tsx, imports/client/components/HuntProfileListPage.tsx, imports/client/components/NotificationCenter.tsx, imports/client/components/OthersProfilePage.tsx, imports/client/components/OwnProfilePage.tsx, imports/client/components/ProfileList.tsx, imports/client/components/ProfilePage.tsx, imports/client/components/RTCDebugPage.tsx, imports/lib/models/MeteorUsers.ts, imports/lib/schemas/User.ts, imports/server/addUserToDiscordRole.ts, imports/server/api/resources/users.ts, imports/server/discordClientRefresher.ts, imports/server/guesses.ts, imports/server/hooks/DingwordHooks.ts, imports/server/hooks/DiscordHooks.ts, imports/server/hunts.ts, imports/server/migrations/38-consolidate-profiles.ts, imports/server/migrations/39-promote-profiles-to-toplevel.ts, imports/server/migrations/all.ts, imports/server/profile.ts, imports/server/puzzle.ts, imports/server/users.ts, types/meteor/accounts-base.ts
Meteor's support for merging different fields on the same object across
multiple subscriptions doesn't work for nested objects, meaning that a
subscription with `fields: {'profile.displayName': 1}` and a
subscription with `fields: {'profile.discordAccount': 1}` will clash,
only returning one of the two fields.
Given that this is a somewhat fundamental restriction on the current
Meteor DDP protocol, the easiest solution is to promote the fields from
the user profile to top-level themselves.
=> Move profile fields to top-level of Meteor.User

imports/client/components/HuntApp.tsx, imports/client/components/HuntProfileListPage.tsx, imports/client/components/Routes.tsx, imports/client/main.tsx, package-lock.json, package.json, tests/acceptance/authentication.tsx, tests/acceptance/lib.ts, tests/acceptance/smoke.tsx, tests/main.ts
I'm not entirely sure how useful this will prove to be, but it feels just a little bit better than having nothing at all. This introduces a test which enumerates all routes and attempts to load each of them (using fixture data to populate the substitutions). If loading the page throws an exception, that will cause the test to fail (even though our error boundary will display the exception, it still gets rethrown as an uncaught exception which mocha picks up on).
In order to support this, I needed to get our routes into a format that I could manipulate, so I first migrated all of our routes into the `Routes.tsx` file (which is relatively straightforward using react-router's concept of [outlets](https://reactrouter.com/docs/en/v6/api#outlet) for rendering nested routes); and I switched to …
=> Add a basic smoke test that all routes work

imports/server/migrations/38-consolidate-profiles.ts
If a server:
* has users with separate Profile objects (any server with users)
* has not applied migration 38 yet
* attempts to apply migration 38 with code built at current git HEAD
then it will fail:
```
Error: After filtering out keys not in the schema, your modifier is now empty
at doValidate (packages/aldeed:collection2/collection2.js:431:11)
at Collection.Mongo.Collection.<computed> [as update] (packages/aldeed:collection2/collection2.js:199:14)
at imports/server/migrations/38-consolidate-profiles.ts:38:7
at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1137:16)
at Cursor.<computed> [as forEach] (packages/mongo/mongo_driver.js:923:44)
at Object.up (imports/server/migrations/38-consolidate-profiles.ts:29:5)
at migrate …
```
=> Fix migration 38 for servers that take migration 38 and 39 in one code update

tests/acceptance/smoke.tsx
We've been seeing some tests fail in CI, and others that are pretty
close to the 2000ms default timeout, so give things a little more
breathing room so perf issues don't flakily block submission or rollout.
=> Bump smoke test timeouts

imports/server/migrations/38-consolidate-profiles.ts
Apparently we also need `filter: false` to make collection2 not filter
out keys that the schema no longer declares.
=> Fix migrations (attempt 2)

imports/server/api/resources/users.ts
This query got overlooked when we exploded profile subfields onto the
user object directly.
=> Fix users API endpoint lookup by google account

tests/acceptance/smoke.tsx
Looks like we saw timeouts in some of the dependabot tests while creating fixtures:
```
#25 235.7 I20220131-15:12:46.167(0)?   routes
#25 235.8 I20220131-15:12:46.276(0)? Failed login attempt: user= email= ip=127.0.0.1 error="You've been logged out by the server. Please log in again."
#25 236.1 I20220131-15:12:46.564(0)? Reset database
#25 236.2 I20220131-15:12:46.647(0)? Reset database
#25 236.4 I20220131-15:12:46.938(0)? [Jykc5WEjn5etAsyTS] User logged in: email=jolly-roger@deathandmayhem.com user=Jykc5WEjn5etAsyTS ip=127.0.0.1
#25 237.7 I20220131-15:12:48.184(0)?     1) "before all" hook in "routes"
#25 237.7 I20220131-15:12:48.186(0)?   11 passing (5s)
#25 237.7 I20220131-15:12:48.187(0)?   1 failing
#25 237.7 I20220131-15:12:48.188(0)?   1) routes
#25 237.7 I20220131-15:12:48.189(0)? …
```
=> Bump timeout on setup for smoke test

imports/client/components/PuzzleAnswer.tsx, imports/client/components/Tag.tsx
Remove punctuation that one might find in a sentence or title from answers in respaced presentation. `.?!,;:-_()'"` are treated comparably to spaces. This is a deliberately short list, so that unexpected but contentful characters (such as emoji) aren't removed in the respaced presentation.
This is another step towards allowing our canonical answer stores to be as semantically meaningful as possible, without detracting from at-a-glance length comparison and indexing. An interface allowing operators to adjust answer spacing and punctuation was proposed in #600.
Closes #602
Canonical presentation (unchanged):
Respaced presentation
=> Remove punctuation from respaced presentation

imports/client/components/CallSection.tsx, imports/client/components/ChatPeople.tsx
Chat people tooltips formerly opened on the right and were unconstrained by the viewport. They now open on the bottom instead of the right (for better consistency with other popovers, which open vertically) and shift laterally to stay within the chat area. If necessary, they spill over to the right, over the document.
Closes #606.
=> Constrain chat people popover

imports/client/hooks/persisted-state.ts, package-lock.json, package.json
(And drop some of our own type declarations meant to work around the older version.)
This replaces #667.
=> Update @types/use-persisted-state to 0.3.1

imports/Flags.ts, imports/client/components/HuntApp.tsx, imports/client/components/HuntListPage.tsx, imports/lib/models/FeatureFlags.ts, imports/lib/permission_stubs.ts, imports/server/users.ts
We're already auto-publishing fields on user, so we might as well skip
the explicit publishes we were using before. For feature flags, Meteor
will auto-publish to the client any subscription with a null name, so we
don't need an unconditional subscribe (because Meteor will do it for
us).
=> Take advantage of autopublish for some cleanup

imports/client/components/PuzzleListPage.tsx, imports/client/components/RelatedPuzzleGroup.tsx, imports/client/hooks/persisted-state.ts
This includes the collapse/uncollapsed state of individual groups as
well as the group/unlock preference. In order to prevent proliferation
of localStorage keys, everything is switched to use-persisted-state and
grouped under a single key as a data structure.
To avoid confusion when searching, we ignore the collapse state of all
groups when showing any search results. And in order to avoid needing to
do a bunch of clicks, there's a new "expand all" button that will expand
any collapsed groups.
Fixes #595.
=> Store all puzzle list state in localStorage

imports/client/components/Puzzle.tsx, imports/client/components/PuzzleActivity.tsx
Increased the spacing between activity monitor items a little bit, and adjusted the column width so it wouldn't overflow.
Moved the call activity icon to the third position, and hid it if there's never been a call.
In the audio icon's previous (second) position, it was a choice of either having the margin between the items look unbalanced (as the differing volume icons change width quite a bit) or having activity elements move as values change. Neither of those seemed like a good idea. By moving it third, we only have to worry about the icon's left margin relative to the other icons and can reserve a fixed width for the icon to appear in if it is absent. Plus it makes it easier to differentiate puzzles with calls from puzzles without at a glance!
=> Tweak puzzle activity monitor

imports/client/components/ActionButtonRow.tsx, imports/client/components/OwnProfilePage.tsx, imports/client/components/SetupPage.tsx
Save buttons feel like they should always be at the bottom right of the
form they're modifying.  To keep them from getting lost, we should limit
the max-width of forms.
Large amounts of text (like that on the SetupPage) is also easier to
read when slightly narrower, and there's less of an argument for
information density on that page vs the PuzzleListPage, so I limited the
width of the content of each section..
I also took the opportunity to slightly tweak the design on SetupPage,
making the section headers fill the full width, making the toggle button
pairs into a reusable component, and adjusting some padding to avoid
buttons right on the edge of their containing element.
=> Rework forms to limit width and put buttons right

imports/client/components/HuntApp.tsx, imports/client/components/HuntEditPage.tsx, imports/client/components/HuntListApp.tsx, imports/client/components/HuntListPage.tsx, imports/client/components/Routes.tsx
As we add more hunt configuration, we're rapidly outgrowing what's
reasonable to put into a relatively small modal. Given that, push it to
a separate page.
This is mostly pure copy-paste of the old modal content, but with a few
changes - namely handling breadcrumbs and URL parameters (instead of
having a hunt passed in), and slight changes to the post-submit flow.
Instead of closing the modal, we take different behavior depending on
whether we're creating a new hunt or editing an existing one. For
creation, we redirect to the newly created hunt. For edits, we scroll to
the bottom of the page and display a banner confirming that the edit was
successful, with a back button to take you back to the hunt list.
=> Move hunt creation/edit to a separate page

imports/client/components/SetupPage.tsx
Without forcing an approval prompt, Google OAuth will only return a
refresh token the first time that you connect an application. If, for
whatever reason, you reconnect the application, Google will do a fast
no-prompt auth and won't return a refresh token, which is unfortunate
since that's the only credential we actually use.
By forcing the approval prompt, we ensure that we always get a refresh
token.
=> Force approval when getting Drive access

imports/client/hooks/persisted-state.ts, package-lock.json, package.json
This is almost completely uneventful, but is newly strict about indexed
access to an empty object, so tweak a cast slightly.
~(Also requires taking some updates to the TypeScript/ESLint integration to pick up versions that are compatible with TS 4.7)~ Bah I thought my working copy was up to date but apparently it was not.
Supersedes #861
=> Upgrade to TypeScript 4.7

tests/unit/imports/lib/relativeTimeFormat.ts
When running tests interactively in a browser (e.g. opening your
personal Chrome instance, not just using the HeadlessChrome from
`meteortesting:mocha`), if your locale observes DST, one test in
particular (the last of the 'formats correctly with multiple items'
suite) fails because the duration is different by one hour (the delta is
one hour longer).  In the full-browser environment, `process.env.TZ`
doesn't exist, and modifying it does not change the locale.  Instead, we
can just use `Date.UTC` to make the test explicitly UTC-oriented, which
avoids the off-by-one-hour issue in this unit test.
Also, this test suite was not actually correctly named -- probably a
copy-paste error from when this was first created.  So fix that while
we're here.
=> Make relativeTimeFormat tests pass in browser too

.github/dependabot.yml
By default, Dependabot will only open a maximum of 5 simultaneous PRs, but given
how quickly the node ecosystem moves, it's often the case that updates are
stalled behind others, so let's try and unblock the flow a little.
=> Allow dependabot to open more pending PRs at once

imports/client/components/AnnouncementsPage.tsx, imports/methods/TypedMethod.ts, imports/methods/postAnnouncement.ts, imports/server/announcements.ts, imports/server/methods/postAnnouncement.ts, server/main.ts
@zarvox I'm curious if you think this is a good idea. If so I'll work on converting the rest of our methods.
mdg:validated-method gives us a handful of affordances that are missing in our current method declaration setup, and I think they're probably worth adopting. Most useful for us is that methods can be invoked as functions with named arguments and types on arguments and return values instead of as strings with unknown positional arguments.
There are some drawbacks - we lose some typechecker-enforced assurances about argument validation. Our previous house style declared the types of all method arguments as `unknown` and relied on `check` functions to make type assertions. There's no similar construct here - we can still declare the arguments to `validate` as type `unknown`, and we …
=> Experiment with using ValidatedMethod

imports/lib/schemas/Puzzle.ts
c3ffbee79cc53ea2eb184a8f99c76e0cc4ffa4af seems to have introduced a
regression in which every subsequent update to a `Puzzle` that does not
specify an explicit value for `answers` winds up causing `answers` to
be set to `[]`, stripping the denormalized answer values, which leads
PuzzleListPage to render it as unsolved (since PuzzleListPage relies on
the denormed `answers` rather than `Guess`es.
The real purpose of this `autoValue` implementation is to uppercase all
the answers.  We do not rely on it to backfill `answers: []` in the
event a caller did not provide that key.  To that end, we should return
`undefined` rather than `[]` from our `autoValue` implementation.
We can also take this opportunity to remove the support for converting a
single string value into an array.  Migrations 20 …
=> Keep previous `answers` value on Puzzles update

imports/client/components/CallSection.tsx, imports/client/components/ChatPeople.tsx
> Given mediasoup-client's native support for pausing/unpausing the producer, I think this is superfluous (and additionally, may be triggering bad behavior from Safari).
> 
> This addressed #603 in my testing.
FWIW, ^ was what I wrote in January when I pulled this commit together. I'm not sure why I didn't submit it for merging at the time, and I can no longer remember what I did to reproduce the issue "in my testing," or if I was even able to.
In any case, I think this change is worst-case harmless, as mediasoup-client _will_ stop sending data when a producer is paused (if you want to see how it threads through, [the `Producer` emits an event](https://github.com/versatica/mediasoup-client/blob/v3/src/Producer.ts#L329-L340) which [is caught by the …
=> Drop the gain node for mute/unmute

imports/client/components/ChatPeople.tsx, imports/client/components/PuzzleActivity.tsx, imports/client/components/RelativeTime.tsx, imports/lib/relativeTimeFormat.ts, tests/unit/imports/lib/relativeTimeFormat.ts
Was browsing through the code and remembered that I wanted to pull this together.
Previously `relativeTimeFormat` returned a static string, and any component that used it would need to set its own timers to re-render as it changed. Instead, this introduces a `RelativeTime` component which automatically re-renders whenever the output of `relativeTimeFormat` would change.
In order to support this, `relativeTimeFormat` now has a "complete" variant which additionally returns how long until the output would change (which is fairly easy to calculate, as we already have the "remainder" lying around). And to facilitate that change, I unified the "terse" and non-terse versions into a single method so that the logic could be shared. (Slightly confusing in the context of this PR, "complete" here is …
=> Better relative time helpers

imports/server/GlobalHooks.ts, imports/server/hooks/TagCleanupHooks.ts
Once a puzzle is solved, it is very unlikely that `needs:` tags are
still relevant.  We can remove them automatically once the puzzle has as
many answers as `expectedAnswerCount`.
Fixes #608.
=> Remove `needs:*` tags when puzzle fully solved

.eslintrc.json, imports/client/components/Puzzle.tsx, imports/client/components/PuzzlePage.tsx
Without this patch, attempting to update a puzzle from the puzzle edit
modal (either on the PuzzlePage or the PuzzleListPage) results in a 400
error.
These callsites were incorrectly passing the additional argument
`huntId`, which is included in `PuzzleModalFormSubmitPayload` but not
accepted by the `updatePuzzle` method.
It is not clear to me why the typechecker didn't complain about passing
an incompatible type here, but maybe that's because in a structural
types world the extra key is permitted.
=> Fix `updatePuzzle` callers

imports/client/components/Puzzle.tsx, imports/client/components/PuzzlePage.tsx, imports/lib/ValidateShape.ts, imports/lib/models/Base.ts, imports/methods/TypedMethod.ts, tests/main.ts, tests/unit/imports/lib/ValidateShape.ts
Since we generally require exact object matching when validating
TypedMethod arguments, we don't want to accidentally accept extra fields
in the argument type. By using ValidateShape, we can catch this at the
type level.
=> Use ValidateShape for TypedMethod calls

.meteor/packages, .meteor/versions, package.json, tsconfig.json
This package is designed to allow for Meteor packages to ship their own types. At this point, I don't think there are any packages that use it, so it's effectively a noop change, but in theory it might see adoption in the future, which would allow us to reduce our dependence on adding our own ambient type declarations for Meteor libraries.
=> Install and configure zodern:types

cloudformation/.gitignore
This dates from before CloudFormation natively supported YAML and should
have been removed as part of 762ad183d09fb6a1284fe79c3829b124edf0f05b.
=> Remove an old gitignore file

imports/client/components/AudioConfig.tsx, imports/client/components/CallSection.tsx, imports/client/components/ChatPeople.tsx, imports/client/components/PuzzlePage.tsx, imports/client/hooks/useCallState.ts
This replaces the hierarchy of components that managed our WebRTC
interactions with a new `useCallState` hook which encapsulates all of
the call state management functionality.  This provides a key benefit:
we can hoist the actual state storage higher in the component tree,
which means that we won't lose call state when switching layouts between
desktop and mobile screen widths.
As a bonus, this change also corrects a bunch of things from the audio
calls implementation that would have gone awry under `StrictMode` in
React 18 due to doing side-effectful actions outside of `useEffect`
blocks.
Fixes #594.
=> Reimplement WebRTC controls as a hook

scripts/run_jolly_roger.sh
I have a VM that has too much RAM to not get opted into auto-clustering, but I also run mongo on it and it has too few resources to handle the write load of a bunch of backends, so I'd like to be able to explicitly opt out of auto-clustering via setting an environment variable on the docker instance.
I decided it was probably appropriate to allow a server operator to override the `HTTP_FORWARDED_COUNT` for their deployment too, so that's here as well.
=> Allow overriding more env vars in run script

imports/lib/schemas/Announcement.ts, imports/lib/schemas/Base.ts, imports/lib/schemas/ChatMessage.ts, imports/lib/schemas/ChatNotification.ts, imports/lib/schemas/Document.ts, imports/lib/schemas/FolderPermission.ts, imports/lib/schemas/Guess.ts, imports/lib/schemas/Hunt.ts, imports/lib/schemas/PendingAnnouncement.ts, imports/lib/schemas/Puzzle.ts, imports/lib/schemas/Tag.ts, imports/lib/schemas/User.ts, imports/lib/schemas/mediasoup/CallHistory.ts, imports/lib/schemas/mediasoup/ConnectAck.ts, imports/lib/schemas/mediasoup/ConnectRequest.ts, imports/lib/schemas/mediasoup/Consumer.ts, imports/lib/schemas/mediasoup/ConsumerAck.ts, imports/lib/schemas/mediasoup/Peer.ts, imports/lib/schemas/mediasoup/ProducerClient.ts, imports/lib/schemas/mediasoup/ProducerServer.ts, imports/lib/schemas/mediasoup/Room.ts, imports/lib/schemas/mediasoup/Router.ts, imports/lib/schemas/mediasoup/Transport.ts, imports/lib/schemas/mediasoup/TransportRequest.ts, imports/lib/schemas/mediasoup/TransportState.ts, imports/lib/schemas/regexes.ts, imports/lib/schemas/typedSchemas.ts, imports/lib/schemas/validators.ts, imports/server/schemas/APIKey.ts, imports/server/schemas/Subscriber.ts
For a couple of reasons, `simpl-schema` upstream has removed their copy of these regexes in the latest version, which we'd like to be able to upgrade to.  To unblock taking that upgrade, instead of relying on `SimpleSchema.RegEx`, define our own equivalent regexes (for Id and Email) and a custom validator for Url that just attempts to construct a URL object (since that regex was vulnerable to regex DoS attacks).
Unblocks #1050.
=> Define our own Id, Email, and Url validation

imports/server/migrations/dropIndex.ts, package-lock.json, package.json
This requires two fixes to account for TypeScript 4.8 being stricter about generic functions. If you take a generic parameter and pass it to a generic function, your generic needs to be as strict as the declaration of the function.
For our `dropIndex` function, this is a semi-easy fix, although it's hard to get at the `Document` type in the upstream mongodb library without declaring an otherwise unnecessary dependency, so we just copy-paste it here (it's fairly simple).
For `@restart/ui`, we need to manually override `react-bootstrap`'s dependency for the time being, which is done by manually editing `package-lock.json` and then letting `npm` clean it up. (With NPM 8, this is natively supported, but Meteor isn't there yet.)
=> Upgrade to TypeScript 4.8.4

imports/client/components/NotificationCenter.tsx, imports/client/components/RTCDebugPage.tsx, imports/client/hooks/breadcrumb.tsx, imports/client/main.tsx, package-lock.json, package.json, tests/acceptance/authentication.tsx, tests/acceptance/smoke.tsx
React 18 introduces a new root API which replaces `ReactDOM.render` as discussed in https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-client-rendering-apis .  Switching to the new root API enables concurrent mode.
Concurrent mode introduces some potentially surprising observable behaviors, which `<StrictMode>` is designed to help developers catch.  Most notably, in concurrent mode, React may call a render function, `setState()`, or reducer dispatch function multiple times during a single update cycle.  Code which relies on a 1-to-1 mapping between `render()` and effect calls will likely break, as will code which performs side-effects in `render()` or in a reducer (including within a `setState` function body).  More about what StrictMode does can be found at …
=> Update to React 18 and enable StrictMode

.meteor/packages, .meteor/versions, imports/client/components/CallSection.tsx, imports/client/components/FirehosePage.tsx, imports/client/components/GuessQueuePage.tsx, imports/client/components/NotificationCenter.tsx, imports/client/components/OthersProfilePage.tsx, imports/client/components/Puzzle.tsx, imports/client/components/PuzzleListPage.tsx, imports/client/components/PuzzlePage.tsx, imports/client/components/RTCDebugPage.tsx, imports/client/components/RelatedPuzzleList.tsx, imports/client/components/RelatedPuzzleTable.tsx, imports/client/components/SplitPanePlus.tsx, imports/client/components/Tag.tsx, imports/client/hooks/useCallState.ts, imports/lib/listUtils.ts, imports/lib/puzzle-sort-and-group.ts, imports/lib/throttle.ts, imports/server/mediasoup.ts, imports/server/methods/configureOrganizeGoogleDrive.ts, tests/acceptance/lib.ts, tests/unit/imports/lib/puzzle-sort-and-group.ts, types/meteor/xolvio/cleaner/cleaner.d.ts
It seems that the Meteor ecosystem is moving away from underscore, at least on the client-side, which means that if we finish removing some of our remaining uses of it, we might be able to save a decent chunk of code size on the client.
This PR removes our remaining direct usages by reimplementing the relevant subset of functionality, and also removes one indirect usage via `xolvio:cleaner` by reimplementing the single serverside function we call directly.  (This also affords us the opportunity to move some of those DB interactions to use non-deprecated methods and async/await while we're there).
The one big remaining dependency that appears to be pulling in `underscore` on the client side is `meteorhacks:cluster`, which is probably a large enough rewrite that we should take it on as a …
=> Remove all direct (and some indirect) uses of underscore

imports/client/components/Tag.tsx, imports/client/hooks/useCallState.ts
One tiny win (3k removed) from popperjs/core and one bigger one (200k deferred) from loading `mediasoup-client` only once the user is actually trying to join a call and needs to create a mediasoup `Device`.
Bundle size before: 1.75MB
Bundle size after: 1.52MB
=> Bundle size reductions

cloudformation/jolly-roger.yaml
Launch templates are AWS's newer way of specifying an instance and are replacing launch configurations. AWS recently sent out a notice that new instance types won't be supported in launch configurations going forward, so it's time for us to switch. The migration is fairly straightforward, although it does require an extra layer of indentation (thanks, YAML) which makes the diff look worse than it is. It's pretty minimal with a word diff.
=> Migrate from launch configurations to launch templates

client/stylesheets/_theme.scss, imports/client/components/styling/responsive.tsx
Bootstrap stopped including the widths for the grid breakpoints in v5. They're scheduled to be readded in v5.3 (with new names); in the interim, we can duplicate the logic.
=> Update responsive breakpoints for BS v5

imports/client/components/CallSection.tsx, imports/client/hooks/useCallState.ts, imports/lib/schemas/mediasoup/Peer.ts, imports/server/mediasoup-api.ts
This improves the experience of using audiocalls that have a whole bunch of people listening in at once.
We achieve this by adding a field on `Peer` that indicates the server's desired stream states, and then having the client respect that, showing a popover message if the server has requested they be muted.
To avoid producing strange effects on server disconnection, we also track more explicitly if we're creating a Peer where the same hunt/call/tab had already joined that call (indicating reconnection on server failure/disconnection, rather than initial join), and if so, propagate the last-known state from the previous Peer record (since we'd like for reconnections not to perturb client state).
Fixes #501.
=> Mute when joining a large call

imports/server/getOrCreateTagByName.ts
This should increase convenience but also help with discoverability of `meta-for:` functionality.  `meta-for:` carries a lot of helpful behavior (grouping, sort ordering, chat dispatch) but is also rather undiscoverable without knowing a priori the magic tag structure.
=> Ensure `meta-for:` tag when creating `group:` tag

imports/client/components/ModalForm.tsx, imports/client/components/PuzzleModalForm.tsx
Fixes:
* a bug where after creating a puzzle, we failed to dismiss the modal
* a React warning about switching between controlled and uncontrolled inputs resulting from passing `value={undefined}`
=> Fix a couple small UI bugs

Dockerfile
It turns out that the behavior of Dockerfile heredocs with an explicitly specified interpreter (i.e. `RUN <<EOF bash`) is a bit wonky and hard to understand. Much clearer is putting a shebang line in the heredoc - docker will handle that by spitting out a temporary file and executing it; much clearer.
However, that doesn't seem to work with whitespace stripping, so just unindent everything instead.
And finally, for consistency, switch all of the scripts to use bash (instead of the few cases where we were using dash) and make sure to set pipefail everywhere - even if it's not necessary, it's a good belt-and-suspenders protection.
=> Fix up Dockerfile

Dockerfile
Now that we are no longer blocked on Debathena giving us a build of moira for modern releases, we can upgrade to jammy without a ton of work. A few specific changes:
* The `apt-key` command has been deprecated, in favor of just dropping files into `/etc/apt/trusted.gpg.d/`. However, this lets us drop our dependency on the `gnupg` package, as we were never using it directly.
* Ubuntu's `chromium-browser` package is now just a wrapper around a snap package, so we can't use that to ensure we have the dependencies for puppeteer. Instead, add the Google Chrome apt repository so we can get metadata on what Chrome-like dependencies look like (but don't actually install Chrome).
=> Upgrade Docker build to Ubuntu 22.04

cloudformation/jolly-roger.yaml
(As per usual for CloudFormation changes, this is already running in production without incident)
=> Upgrade hosts in CloudFormation to jammy

imports/client/components/PuzzlePage.tsx
Range inputs don't support having an "unset" state, but we can simulate one with a boolean field that we set to true when someone changes the value. With this information, we can ensure that someone explicitly chooses a direction and confidence before submitting a guess, which is useful both in real time for operators evaluating guesses and for the post-game analysis.
Fixes #301.
Here's what it looks like:
https://user-images.githubusercontent.com/28167/206561192-c3de5238-f510-46db-a3eb-ea05cc6df523.mov
=> Require explicit guess direction/confidence

.eslintrc.json, Dockerfile, imports/client/components/SetupPage.tsx, imports/lib/models/DocumentActivities.ts, imports/lib/models/facade.ts, imports/lib/schemas/DocumentActivity.ts, imports/lib/schemas/facade.ts, imports/server/gdriveDocumentWatcher.ts, imports/server/migrations/41-document-activities.ts, imports/server/migrations/all.ts, imports/server/models/DocumentWatches.ts, imports/server/schemas/DocumentWatch.ts, package-lock.json, package.json, server/main.ts, types/ngrok.d.ts
This uses the Google Drive API's `files.watch` API method to receive webhooks when changes are made to a document. We setup a watch on every document in the database and handle renewing it as necessary.
When we're notified by Google that a document has been changed, we store a record in the database - effectively a tuple of `(timestamp, document)`. Absence of a record indicates lack of activity.
Google's notifications aren't especially timely - in practice they seem to send notifications at about 3 minute granularity - so we use 5 minute granularity for our own tracking. It's a nice round number, and pretty well approximates the granularity of the notifications.
Activity records are currently never garbage collected. This should be safe because generally puzzles don't see constant …
=> Track activity on Google Drive documents

imports/FixtureHunt.ts, imports/client/components/GuessQueuePage.tsx, imports/client/components/NotificationCenter.tsx, imports/client/components/PuzzlePage.tsx, imports/lib/schemas/Guess.ts, imports/server/methods/createFixtureHunt.ts
First round of improvements to the guess state machine.
The eventual goals are:
- Allowing guesses to have an "intermediate" state (short for "correct intermediate answer"). This state can be used when we receive a cluephrase or instruction that has been validated by HQ; we know it's correct, but it's not a solution to the puzzle. (Re: #231)
- Allowing guesses to capture additional notes from the operator beyond state. This is useful for intermediate answers to capture any additional instructions we receive from HQ ("send your video here" - we'll add some examples to the fixture data) and for rejections to capture why the operator rejected the answer.
- Allowing operators to modify the spacing of a guess, in order to reflect the canonical representation of the answer that we get back from …
=> Guess Improvements: Round 1

imports/server/gdriveDocumentWatcher.ts, package-lock.json, package.json
First, when we re-create the document watcher, make sure we clean up the old timeouts we set. Second, use the p-throttle library to limit the number of requests we have open at a time.
=> Fix document watches to try and avoid spamming everyone

imports/client/components/NotificationCenter.tsx, imports/server/JoinPublisher.ts, imports/server/guesses.ts
These are conceptually separate changes, but they wind up touching the same lines in the same file, so for expedience they're in this PR together.  If desired, I can pull them apart.
The first change drops our custom-rolled notifications and switches to using [Toasts](https://react-bootstrap.netlify.app/components/toasts/).  While I was poking at it, I realized that it might make more sense to put the inbound notifications at the bottom right instead of the top-right, since that way it would mostly cover spreadsheet or puzzle list (both of which are generally scrollable) rather than the "Add puzzle" or nav UI.  This should help with the primary complaint in #230 (though I think that bug has some other interesting ideas, so I won't close it yet).
The second change adds support for a pretty …
=> Rework NotificationCenter with bootstrap Toast and make guess notifications linger briefly after state change

imports/server/gdriveDocumentWatcher.ts
We're struggling a bit to avoid Google's rate limiting on watch creation. I think in the long term I may have to take another look at `changes.watch` to see if I can set fewer watches and get more data, but in the interim, I'm hoping that this will help jitter things out a little better.
=> Increase Drive watch renewal window in production

imports/client/components/NotificationCenter.tsx, imports/client/components/SpinnerTimer.tsx, imports/server/JoinPublisher.ts, imports/server/guesses.ts
Fixes:
* a sign bug in the client-side refreshing that caused us to busy-loop timeouts updating values until completed guesses were marked (1c119d890f65ff97b081cf4d5867e69405ecbf19)
* incorrect `observeChanges` usages in `JoinedObjectObserver` (2cdb64ee1cdc713a6eb8edb767f0d9786d55b358) which, through spurious `decref`s, was causing us to lose client-side record of the user who submitted a guess on pages where we did not otherwise have that record locally due to another subscription
* incorrect `observeChanges` usages in `PendingGuessWatcher` (32b967d2c9baa148c2e03fd42335c4987930a769) which we probably would never hit since we don't remove the `roles` field but it's good to be correct
Adds:
* a spinner which indicates when a serviced guess will disappear from being shown
What it looks like …
=> Fix multiple guess queue bugs and add countdown spinner

imports/Flags.ts, imports/lib/schemas/FeatureFlag.ts, imports/methods/setFeatureFlag.ts, imports/server/discordClientRefresher.ts, imports/server/mediasoup.ts, imports/server/methods/setFeatureFlag.ts
This eliminates the "random_by" feature flag mode, which as far as I'm aware we have never used, and uses the resulting simplification to introduce a `Flags.observeChanges` helper. I wanted the latter after feeling like I had written that logic too many times (including in #1226; if this lands first I'll update it)
=> Feature flag improvements

client/stylesheets/_theme.scss, imports/client/components/NotificationCenter.tsx, imports/methods/setGuessState.ts, imports/server/methods/setGuessState.ts, imports/server/transitionGuess.ts
This introduces UI for collecting additional notes about a guess as part of transitioning a guess into the "incomplete" or "rejected" state.
Here's what the flow looks like on desktop:
https://user-images.githubusercontent.com/28167/209242450-a26412ee-3c44-46a1-b7e4-c78a6636e79b.mov
and on mobile:
https://user-images.githubusercontent.com/28167/209242465-ccda2a85-ef0d-4b28-a007-6e227a955617.mov
Fixes #231.
=> Guess Improvements: Round 2

imports/client/components/CallSection.tsx
Before this patchset, if another call participant muted you, then when you dismissed the remote mute popup, as the popup animated out, the contents would change from naming the user you were muted by to saying "someone", as the value of `mutedBy` had changed to undefined.
This patch defers clearing the `remoteMutedBy` value in `callState` until after the animation is completed.
Before:
https://user-images.githubusercontent.com/307325/209432530-3aec3042-0d73-4f30-9350-c3804273f1b3.mov
After:
https://user-images.githubusercontent.com/307325/209432537-2c2d5eab-9519-4002-950c-926cd7b5be9a.mov
Special thanks to @aldeka, who pointed out this issue!
=> Avoid changing overlay text during dismiss animation

imports/client/components/NotificationCenter.tsx
The default event handler for Clicking a button with `type="submit"` causes a form submission which causes a navigation.
We could also have kept the `type="submit"` and overridden an event handler to call `preventDefault()` if we wanted to be more semantically-correct, but this seemed simpler.
=> Avoid browser-driven form submission when submitting Rejected reason

imports/client/components/NotificationCenter.tsx
Each of the following ids are used by both the `GuessQueuePage` data table as well as the `NotificationCenter` toast:
- `guess-${guess._id}-direction-tooltip`
- `guess-${guess._id}-confidence-tooltip`
- `guess-${guess._id}-copy-tooltip`
We should avoid reusing ids on the page.  One way to help achieve that is to encode something about the file in which the tooltip appears in the id string itself, so I switched the ones in the NotificationCenter to include `notification-`.
These were the only reused `id`s I found.
=> Avoid use of the same <Tooltip> `id` in multiple places

.eslintrc.json, imports/lib/config/activityTracking.ts, imports/lib/roundedTime.ts, imports/server/GlobalHooks.ts, imports/server/activityTracking.ts, imports/server/gdriveChangeFetcher.ts, imports/server/hooks/ActivityHooks.ts, imports/server/mediasoup.ts, imports/server/migrations/43-puzzle-activity.ts, imports/server/migrations/all.ts, imports/server/models/ConsolidatedActivities.ts, imports/server/models/Locks.ts, imports/server/models/RecentActivities.ts, imports/server/schemas/ConsolidatedActivity.ts, imports/server/schemas/RecentActivity.ts, server/main.ts
As part of addressing #172, we need better time-series data on how many users are working on any given puzzle. This collects that data for calls and chats. Together with the data we already get from documents, this should be enough for us to aggregate and display that data.
The first two commits are mostly cleanup and refactor to support the third commit, which is effectively the crux of this PR. The commit message is (IMO) important enough that I'll just paste it here for reference:
> In order to display chat and call activity data to clients without processing or shipping an overwhelming amount of data, we need to compress it in two ways. First, we need to aggregate multiple operations from a single user within the same time window. Second, we need to aggregate a count of unique users …
=> Collect consolidated activity tracking data

imports/server/mediasoup-api.ts
Adding this as a stop-gap until we get around to #601. This was the biggest piece of information we were missing.
=> Add a log line when a peer leaves a call

imports/server/accounts.ts
The url needs to be treated as safe lest it get escaped again and not function as a working link.  This matches the configured production template.
=> Fix default enroll template

imports/server/schemas/DriveChangesPageToken.ts
This can happen when we hit the end of an iteration loop or when something goes wrong with an iteration.
=> Next Drive changes page token is allowed to be undefined

imports/client/components/SetupPage.tsx
When we reimplemented fetching of document changes, we didn't adjust the feature flag name (or description) on the setup page.
=> Fix feature flag for disabling Google Drive changes

imports/client/components/ModalForm.tsx
We disabled animations for ModalForm due to poor interactions with autofocused inputs. That has since been fixed by upstream, so we can re-enable them.
I'll note that there's a comment saying that disabling the animations makes the UI feel snappier. I think the lack of animations feels a bit abrupt, but I don't have extraordinary strong opinions on the matter. I will accept either merging this PR or closing #406 as wontfix, but we should definitely do one or the other 🙂 
Fixes #406.
Before:
https://user-images.githubusercontent.com/28167/209875983-d1b40734-e5ad-4931-a9cb-6a70a1961dbd.mov
After:
https://user-images.githubusercontent.com/28167/209875993-40560e34-93fb-48c1-ae16-a835963fb86e.mov
=> Revert #404

imports/client/components/CallSection.tsx
In order to avoid the overhead of the remote mute modal until we actually need it, we don't render it to the DOM until we're ready to display it. If it defaults to being hidden when it is first rendered, then you have to click on someone twice in order to mute them.
=> Make RemoteMuteConfirmModal visible on first render

imports/lib/schemas/User.ts, types/user.d.ts
We have a more complete one in `imports/lib/schemas/User.ts`.
Also, follow the convention that `Meteor` is a `namespace`, not a `module`, since that appears to matter once we start using first-party type declarations.
=> Remove duplicate (incomplete) Meteor.User type decl

imports/client/components/HuntEditPage.tsx, imports/client/components/SetupPage.tsx, imports/lib/models/Base.ts, imports/server/accounts.ts, imports/server/addUsersToDiscordRole.ts, imports/server/getTeamName.ts, imports/server/methods/addHuntUser.ts, imports/server/methods/configureOrganizeGoogleDrive.ts, imports/server/methods/linkUserDiscordAccount.ts, imports/server/setup.ts
If we make a query with a literal value, we can use that to infer something about the types of records that will be returned. This is especially useful for the Settings collection, where we often query on the tag of a tagged union.
I think the biggest argument against this change is that the runtime checks ensure that we aren't, e.g., getting back bogus data from the database. But I'd argue that we're in for a bad time if that's happening regardless of whether or not we have runtime checks in place to prevent it.
=> Use queries to narrow down the return type

imports/server/addUsersToDiscordRole.ts
We logged about it, but didn't early-exit, which is really the most important part.
=> Respect `disable.discord` circuit breaker

imports/client/components/PuzzlePage.tsx
We give a client-side warning when a user attempts to submit an answer that has already been submitted. However, this warning only looks for exact equality, meaning that we won't warn if the only difference is whitespace.
Since this is only a warning and not a block, it seems acceptable if this results in some false-positives, but it should have prevented duplicate answers that were ultimately rejected in hunts past.
=> Ignore whitespace when looking for duplicate answers

imports/client/components/PuzzlePage.tsx
> Uncaught TypeError: String.prototype.replaceAll called with a non-global RegExp argument
=> Fix guess validation

imports/client/components/AnnouncementsPage.tsx, imports/client/components/GuessQueuePage.tsx, imports/client/components/HuntApp.tsx, imports/client/components/HuntListPage.tsx, imports/client/components/HuntProfileListPage.tsx, imports/client/components/ProfileList.tsx, imports/client/components/PuzzleListPage.tsx, imports/client/components/PuzzlePage.tsx, imports/client/components/UserInvitePage.tsx, imports/lib/permission_stubs.ts, imports/server/mediasoup-api.ts, imports/server/methods/addHuntUser.ts, imports/server/methods/bulkAddHuntUsers.ts, imports/server/methods/createPuzzle.ts, imports/server/methods/demoteOperator.ts, imports/server/methods/destroyPuzzle.ts, imports/server/methods/postAnnouncement.ts, imports/server/methods/promoteOperator.ts, imports/server/methods/setGuessState.ts, imports/server/methods/undestroyPuzzle.ts, imports/server/methods/updatePuzzle.ts, imports/server/users.ts, tests/acceptance/profiles.tsx
We were still looking up hunts in permission_stubs, so this gets rid of some more synchronous calls that would run on the server-side.
=> Eliminate database queries from permission_stubs

client/stylesheets/app.scss, imports/client/components/GuessQueuePage.tsx, imports/client/components/GuessState.tsx, imports/client/components/ModalForm.tsx, imports/client/components/PuzzleAnswer.tsx, imports/client/components/PuzzlePage.tsx, imports/client/components/guessDetails.tsx, imports/client/components/styling/constants.tsx
A quick breakdown of what this changes:
- Increases the weight for Source Code Pro from 300 to 400 (i.e. "normal") across the board to give answer displays just a little more weight
- Switches away from displaying direction and confidence on the guess queue page as sliders:
This also lets us stick with the full-sized layout down to the "medium" screen size cutoff, instead of "large", so there's less no-man's-land in the middle sizes where the mobile layout looks huuge.
- Dramatically improves how the sliders in the guess modal are rendered. As it turns out, `FormControl type="range"` isn't really intended to work. Here's the before:
and after:
- More or less completely redoes the table of historical guess submissions in the modal on the puzzle page, taking advantage of some of the design …
=> Guess modal improvements

imports/client/components/PuzzleActivity.tsx
A bit between the door and the time.
A bit between the activity count and the sparkline.
The sparkline tooltip now has space on the bottom. I also made the title fit on one line and the time legend is in smaller text.
One thing I'd like but haven't done is make the sparkline labels' baseline match the base of the sparklines. TBD.
Before:
After:
=> Add a bit of padding to puzzle activity UI

imports/lib/schemas/FolderPermission.ts, imports/server/gdrive.ts, imports/server/migrations/45-folder-permission-level.ts, imports/server/migrations/all.ts
As it turns out, granting commenter permission is sufficient for edits to a document to be attributed to that user, instead of being attributed to the owner of the document.
=> Grant commenter permission on hunt folders

.eslintrc.json, imports/client/components/SetupPage.tsx, imports/lib/schemas/User.ts, imports/methods/configureCollectGoogleAccountIds.ts, imports/server/googleClientRefresher.ts, imports/server/methods/configureCollectGoogleAccountIds.ts, imports/server/methods/index.ts, imports/server/methods/linkUserGoogleAccount.ts, package-lock.json, package.json
In order to cross-reference Google Drive activity with Jolly Roger users, we need their account ID, not just their email address, so start capturing it going forward.
To avoid requiring everyone to re-link their Google accounts, introduce a new "configureCollectGoogleAccountIds" Meteor method. This takes advantage of the fact that anyone who has linked their Google account shows up in the "other contacts" API, and we can mine their account ID from there. This should be purely transitional - anyone setting up Jolly Roger in the future shouldn't need to do this - so it's not especially optimized for efficiency (many of the queries are poorly indexed) and there's no UI exposure.
=> Store Google account IDs in addition to emails

imports/client/components/GuessQueuePage.tsx, imports/client/components/PuzzlePage.tsx
Apply background color only to cells of the guess queue, instead of all descendants, to fix a flicker caused by animated button backgrounds. This also restores the expected background color of the button.
@aldeka raised this issue in the Discord.
=> Fix guess queue flicker

imports/client/components/AccountForm.tsx, imports/client/components/HuntEditPage.tsx, imports/client/components/OwnProfilePage.tsx, imports/client/components/PuzzleModalForm.tsx, imports/client/components/SetupPage.tsx, imports/client/components/TagList.tsx, imports/methods/configureDiscordBot.ts, imports/methods/configureDiscordOAuthClient.ts, imports/methods/configureGoogleOAuthClient.ts, imports/methods/configureGoogleScriptUrl.ts, imports/methods/updateProfile.ts, imports/server/methods/configureDiscordBot.ts, imports/server/methods/configureDiscordOAuthClient.ts, imports/server/methods/configureGoogleOAuthClient.ts, imports/server/methods/configureGoogleScriptUrl.ts, imports/server/methods/destroyPuzzle.ts, imports/server/methods/updateProfile.ts
Historically, we've played fairly fast and loose with the distinction between empty strings and undefined - both were false-y, so we'd often treat both equivalently (e.g. by running them through the `||` operator). This was often motivated by React, where having an input with an undefined value is problematic (since React treats it as uncontrolled), so we'd often cast undefined to an empty string.
Of course, they're not equivalent. This has popped up in various ways, including switching more broadly to the nullish-coalescing operator in 4eab028a.
This commit generally looks for places where we cast undefined to empty strings, and ensures that we cast those empty strings back to undefined when we pass them to server code. There were also a few cases where the server code didn't correctly …
=> Improve our handling of empty strings

imports/client/components/NotificationCenter.tsx
Oddly, rejected answers were part of a Form, whereas intermediate correct answers were just in a fragment. Neither used a proper form label, which meant that the label, when clicked, would not focus the input box.
This patchset deduplicates the markup for the two states that support additional notes, and ensures both make correct semantic usage of labels.
Also, I switched from `px` to the ~equivalent in `rem`, since that's the unit that bootstrap uses for margin/padding.
=> More consistency in spacing and markup in notifications

imports/client/components/UserInvitePage.tsx
Otherwise a trailing newline results in us trying to invite the email address "", which goes about as well as you'd expect.
cc @flipdog
=> Strip list of emails in bulk invite

imports/client/components/App.tsx, imports/client/components/GuessQueuePage.tsx, imports/client/components/ModalForm.tsx, imports/client/components/NotificationCenter.tsx, imports/client/components/Puzzle.tsx, imports/client/components/PuzzleAnswer.tsx, imports/client/components/PuzzlePage.tsx, imports/client/components/PuzzleTable.tsx, imports/client/components/styling/Breakable.tsx
In many places, long titles and answers (notably those with very long words) can spill out, especially at mobile widths. Since these potentially unwieldy strings are beyond our control, we need to deal with them gracefully. Quite a few examples are currently affecting past hunts in production.
Affected interfaces (and fields with potential breaks):
- Breadcrumbs
- Breadcrumbs are wrapped to at most two lines and are truncated with an ellipsis if the title overflows vertically or a word overflows horizontally
- Puzzle page (answer)
- Operator guess toasts (title, answer, submitter)
- Toast header breaks with hyphens if possible, but breaks arbitrarily if necessary
- Puzzle list (title, answer)
- Wrapped lines of answers are indented for legibility
- Related puzzles (title, answer)
- …
=> Prevent content spills

imports/server/WorkerPool.ts
In cluster mode, the coordinator process sends incoming websocket connections to a worker process via child_process.send. However, when we ported this code away from meteorhacks:cluster, we didn't add a listener in the child to handle that message. This meant that if we had clustering enabled, we would just silently drop websocket connections. This didn't _break_ things, because we would fall back on XHR, but it's definitely not great.
Bring back a handler for the IPC message in the child.
=> Handle websockets in cluster children processes

imports/lib/schemas/validators.ts
Both Hunt and Puzzle contain a field which is optional, but if present, should be a valid URL.  For both of these objects, when we would perform updates on the object, we `$set` the provided keys and `$unset` the others.  Our custom validator was failing since `this.isSet` was true, and empty-string does not parse as a valid URL.  When `this.operator` is `$unset`, though, we don't care about the value -- unsetting the field is always valid.
=> Fix issue preventing updating Hunt/Puzzle when url absent

.eslintrc.json, client/main.ts, imports/client/bugsnag.ts, imports/client/components/App.tsx, imports/client/lookupUrl.ts, imports/methods/TypedMethod.ts, imports/server/addRuntimeConfig.ts, imports/server/addUsersToDiscordRole.ts, imports/server/assets.ts, imports/server/bugsnag.ts, imports/server/mediasoup.ts, package-lock.json, package.json, scripts/run_jolly_roger.sh, server/main.ts, types/meteor-runtime-config.d.ts, types/meteor/meteor.d.ts
This sets up a basic Bugsnag configuration on both the server (pulling API key from the environment) and client (pulling API key from `__meteor_runtime_config__` shipped by the server). I setup more detailed integration in a few specific places:
- We grab user information when it's available to us
- We use Bugsnag's React error boundary, which captures additional React component information
- We wire up reporting to TypedMethod
- We explicitly report a few exceptions that we previously were logging and otherwise throwing away.
This is probably not everything that we want from a Bugsnag integration. We definitely are not currently getting any reporting on exceptions thrown by publish methods (because wildly Meteor more or less completely throws those exceptions away!). We also _may_ have …
=> Configure Bugsnag client- and server-side error reporting

imports/client/bugsnag.ts, imports/client/components/PuzzlePage.tsx, imports/methods/TypedMethod.ts, imports/server/bugsnag.ts
...and fix a (harmless) bug that @flipdog discovered in `ensurePuzzleDocument`.
I still need to figure out how to get our application source code into Bugsnag. Right now, we see file+line numbers, but they aren't expandable, even though some NPM modules do:
=> Collect additional data in Bugsnag reports

imports/client/components/CallSection.tsx
New "badges" for mute/deafen icons:
The deafen button will still appear if you're in dev mode.
=> Remove "deafen" button for regular users, update mute icons on chatpeople

imports/client/components/ProfilePage.tsx
`loading` can turn true, but since the `useTracker` block does not directly depend on `loading`, `user` could still be cached as `undefined` when React does a rerender until the Tracker autoruns again.
There are several things we can do to be more resilient here:
* don't lie in the type assertion
* handle the case where no user gets loaded at all, which could happen if the URL was incorrect or referred to a non-existent user id.
* put `loading` in the deps list of the `useTracker` block so that a recomputation is forced when loading goes from true to false and a rerender is triggered
Fixing this because I encountered it in production:
=> Fix race condition in ProfilePage

imports/client/components/AnnouncementsPage.tsx, imports/client/components/FirehosePage.tsx, imports/client/components/GuessQueuePage.tsx, imports/client/components/NotificationCenter.tsx, imports/client/components/PuzzleDeleteModal.tsx, imports/client/components/PuzzlePage.tsx, imports/lib/models/MeteorUsers.ts
Consumers of `indexedDisplayNames` need to handle the case where the display name for that user is unset (due to incomplete onboarding, etc.) anyway, and `Map.get()` helps enforce that neatly via return type.
=> Make `indexedDisplayNames` return a Map instead of a Record

imports/server/bugsnag.ts, package-lock.json, package.json
On server-side code, it's not sufficient to be in a Fiber for Meteor.user to be legal to call.
=> Fix exception in Bugsnag collection

.eslintrc.json, imports/server/bugsnag.ts, package-lock.json, package.json
In theory, Bugsnag should be able to fetch these on its own, but in practice it doesn't seem to be happening.
I think there may still be followup work for dynamically imported files - they ship source maps in a different format. Specifically, for the main JS bundle, Meteor uses the `sourceMap` and `sourceMapUrl` properties in the manifest to generate `X-SourceMap` headers. For dynamically imported files, the contents of the files include a `sourceMappingURL` comment, which refers to a file that's served independently. I tried to write some code to upload those as well, but couldn't get it working in the amount of time I had allotted myself to work on this today. I think this is still a useful incremental improvement, though, and worth landing in the interim.
=> Upload client source maps to Bugsnag

imports/server/addUsersToDiscordRole.ts, imports/server/methods/configureCollectGoogleAccountIds.ts, imports/server/methods/configureEnsureGoogleScript.ts
When we were reducing over promises, we would "continue" through the loop with early return, but that doesn't do what we want now that we don't have an iteration function anymore.
Fixes some bugs introduced in #1318, although fortunately I don't think any of these are especially urgent.
=> Fix early returns from promise conversion

imports/client/components/ChatMessageV2.tsx, imports/client/components/FancyEditor.tsx
Mixing the basic formatting options currently causes the preview decorations to be assigned to slightly wrong ranges.  Attempt to compensate.
This will still have some trouble with blockquote line continuations (which I'm not advertising) but it's really hard to do better there because by the time you're in the child you've lost the context of how much of the text you've actually consumed and if there were any decorations involved.  A more principled approach is probably possible, but this fixes the simple cases without being disruptive and can land now.
Also fix a DOM nesting error -- it's not legal to have a `blockquote` be a child of a `p`.
=> Fix (some) nested formatting decorations preview

.eslintrc.json, imports/client/components/NotificationCenter.tsx, imports/client/components/PuzzlePage.tsx, imports/client/hooks/useBlockUpdate.tsx, imports/client/hooks/useCallState.ts, types/meteor/reload.d.ts
When a user is in a call or in the middle of composing a chat message, that's a particularly unfortunate time to reload the page due to a new code push.
So, introduce a new hook that can hold code updates. So long as a non-undefined string is passed to `useBlockUpdate`, any new code push will cause a notification to pop up, but the page won't refresh.
Fixes #1314.
=> Block code reloads when it would destroy state

imports/client/components/FirehosePage.tsx, imports/client/components/PuzzlePage.tsx
Whenever the data returned by a useTracker changes, the entire data set is replaced. This means that even if (e.g.) the only change was adding a new element to an array, all other elements of that array will return new objects, which won't compare as equal to the old objects (even if they have the same contents).
This means in practice that any time (e.g.) a new chat message is created, the entire chat history has to be re-rendered.
By using the useFind hook instead, we can significantly decrease the amount of work required. In my testing, this reduced render time by factor of roughly 10.
=> Prevent rerendering entire chat history

imports/client/components/ChatMessageV2.tsx
* Paragraphs are not allowed to be children of spans.  We had some unnecessary component nesting that caused all markdown ranges to be rendered beneath a span.  Reducing indirection here simplifies the component tree and as a bonus avoids invalid nestings.
* Paragraphs need to render as inline with pre-wrap, not inline-block. If they are inline blocks, then they will tend to refuse to share a line with a mention (which must also be an inline block) which is worse layout.  The initial version of this code rendered paragraphs as a span, which used inline layout, so this fixes a regression I introduced in cea778556903b8480edced0886a13d2e330323d0.
* Ensure that unsupported tag types are rendered as pre-wrap raw text. This helps us do a better job of not letting marked's list-handling cause us …
=> Fix assorted subtle chat message renderer bugs

imports/client/components/NotificationCenter.tsx
Let guess response buttons expand to fill the row, with consistent gaps across the notification. Also fix a div that was a child of a ul.
Does not conflict with #1302, which mostly deals with the header, except that I believe this eliminates the need for the guess detail wrappers proposed there.
Old:
New:
Old (Mobile):
New (Mobile):
=> Improve button flow on guess notifications

imports/client/components/Puzzle.tsx, imports/client/components/PuzzleListPage.tsx, imports/client/components/PuzzlePage.tsx, imports/lib/puzzle-sort-and-group.ts, imports/server/hooks/DiscordHooks.ts, imports/server/hooks/TagCleanupHooks.ts
Helps keep the logic about "is this puzzle solved or not?" in one place rather than scattering it across a bunch of
`answers.length > expectedAnswerCount` invocations across the codebase.
=> Use `computeSolvedness()` when relying on solve state

imports/lib/models/DiscordRoleGrants.ts, imports/lib/models/facade.ts, imports/lib/schemas/DiscordRoleGrant.ts, imports/lib/schemas/facade.ts, imports/server/addUsersToDiscordRole.ts, imports/server/configureLogger.ts, imports/server/methods/syncHuntDiscordRole.ts, imports/server/methods/updateHunt.ts, imports/server/migrations/47-discord-role-grant-indexes.ts, imports/server/migrations/all.ts
Discord has a fairly low rate limit, so blindly attempting to add anyone
in the hunt to a role is a quick road to aggressive rate limiting.
Instead, keep track of who we've previously granted a role to (similar
to what we do for Google Drive permissions) and avoid trying to re-grant
them their role.
However, while we populate the cache any time we add a user to a role,
we only check the cache for the syncHuntDiscordRole method (and for the
updateHunt method). In any other case, we're acting on behalf of a
specific user, and we should take action for them even if we might have
done it already (to ensure they don't get stuck in a bad state
accidentally).
And while it's not my preferred solution, arguably this does fix #1296.
(There's also a fix for the logger configuration on the …
=> Cache Discord permission grants to limit rate limiting

imports/client/components/GuessQueuePage.tsx, imports/client/components/PuzzlePage.tsx
Per discussion with @ebroder add rules between guesses in grid presentations (and remove existing outline around every cell in the guess submission modal).
=> Add rule lines between guesses in grids

imports/server/addUsersToDiscordRole.ts
We're still seeing rate limiting. In practice, it seems to be happening after roughly 20 requests, but we don't need this to finish quickly so let's just slow ourselves wayyyy down.
=> Rate limit Discord calls more aggressively

imports/lib/dingwordLogic.ts
Hopefully this reduces spurious dinging for things like "description" triggering on "script", as described in #597.
Also ensure that the dingwords themselves are lowercase before attempting to match.  We do this client-side on OwnProfilePage when setting dingwords, but it's probably good to ensure serverside too.
=> Only ding on matches at start-of-word

imports/client/components/PuzzleListPage.tsx
- Fix wrapping and spacing
- Replace show solved toggle button with button group choices
- Replace operator interface toggle button (formerly appended to add puzzle) with button group choices
- Move filter results below filters and above results, providing a logical flow
- Improve styling in very narrow viewports (e.g. iPad Split View)
Wrapping and breakpoints:
- For operators, the search bar always gets its own line to make room for extra controls. For other users, this doesn't happen until the sm breakpoint.
- For operators, controls are rearranged into a grid below the xs breakpoint.
- Below 360px, controls are presented one per row.
Tested in Safari, Chrome, Firefox.
**Old Desktop-Operator**
**Old Mobile-Operator**
**New Desktop-Operator**
**New Mobile-Operator**
**New …
=> Improve puzzle list page controls

imports/client/components/FirehosePage.tsx
FirehosePage is particularly expensive to reload, so if you're following the links on it, you probably don't actually want to navigate away. Open them in separate tabs instead.
Fixes #1357.
=> Open puzzle links from FirehosePage in new tab

imports/server/hooks/ChatHooks.ts
Don't send puzzle-in-round-solved notification to the puzzle that was just solved.
Fixes #1356.
=> Avoid useless puzzle-in-round-solved notification

imports/lib/models/Base.ts, tests/main.ts, tests/unit/imports/server/Base.ts
Because of how Meteor currently implements their async methods, they call into our implementation of `findOneAsync`, which injects the deleted=false term to all queries, including those where we explicitly want deleted (or both deleted and non-deleted) objects.
The easiest way to work around that right now is to implement our own versions of the async methods in the same style as Meteor's - simply wrapping the synchronous versions.
This will eventually break as Meteor continues to migrate towards async implementations by default, so add a test that will fail if and when that happens.
I did verify in local testing that the tests failed when I didn't apply the patch to `Base.ts`:
```
I20230117-13:11:23.737(-5)?   1) Base
I20230117-13:11:23.737(-5)?        findOneDeletedAsync …
```
=> Fix findOne{,Allowing}DeletedAsync methods

imports/client/bugsnag.ts, imports/client/components/NotificationCenter.tsx, imports/lib/permission_stubs.ts, imports/server/bugsnag.ts, tests/acceptance/profiles.tsx
The previous behavior was that NotificationCenter would show any pending guess that was visible to the client.  This is slightly too broad: when viewing a puzzle, all guesses for that puzzle are fetched, regardless of state, so if you were an operator in hunt A you'd see the guesses for a puzzle you had open in hunt B, even though you can't action them.
Instead, we should have NotificationCenter filter guesses down to those that the user can action, which is the set of those from hunts the user is an operator for.
Fixes #1353.
=> Don't show guesses in guess queue for hunts you don't operate

imports/client/components/CallSection.tsx
We tell people they should leave and re-join the call, but we don't give them a way to do that.
Before:
After:
=> Show "leave call" button when in a bad state

imports/client/components/GuessQueuePage.tsx, imports/client/components/NotificationCenter.tsx, imports/server/methods/removePuzzleAnswer.ts, imports/server/methods/setGuessState.ts
We will simply pretend that they do not exist, and avoid showing them in the UI.
We also prevent taking actions on such Guesses -- we don't want to wind up running solved/unsolved hooks, and it's somewhat nonsensical to try to transition the guess state of a Guess that isn't displayed anywhere anyway.
Fixes #1371.
=> Hide `Guess`es that reference deleted `Puzzle`s

imports/lib/models/mediasoup/MonitorConnectAcks.ts, imports/lib/models/mediasoup/MonitorConnectRequests.ts, imports/lib/schemas/mediasoup/MonitorConnectAck.ts, imports/lib/schemas/mediasoup/MonitorConnectRequest.ts, imports/server/garbage-collection.ts, imports/server/mediasoup.ts
I don't plan to merge this until after this weekend, but I'll open this as a draft for feedback in case you have time to read through it.
Instead of heartbeating through MongoDB writes, we can use Mediasoup data producers and consumers to heartbeat between servers directly.
Each server creates a dedicated router for handling heartbeats; a DirectTransport, which allows the Meteor process to send data packets back and forth to the Mediasoup worker without a full WebRTC negotiation; and a DataProducer over that DirectTransport, which emits a heartbeat packet every 100ms (+/- jitter).
Then, whenever a server notices another server in the list of servers, it establishes a PipeTransport connection to that other server and pipes the heartbeat producer over that transport. It creates a …
=> Use Mediasoup to heartbeat between servers

imports/client/components/HuntListPage.tsx, imports/client/components/PuzzlePage.tsx, imports/client/hooks/useCallState.ts, imports/methods/TypedMethod.ts
This catches any Meteor method exception and reports it to Bugsnag. This will be duplicative with our server-side reporting, but we generally have significantly better contextual information on the client, which should make debugging easier.
Additionally, add breadcrumbs on method calls so we can better tell what was happening immediately prior to an error.
(I also dropped the places where we were only catching a method error so that we could report it to Bugsnag, since this will catch all of those now)
=> Add additional client-side Bugsnag reporting

imports/server/discord.ts, imports/server/mediasoup-api.ts
As of Meteor 2.9, the OAuth package supports async functions (and publications have for a while).
(Last non-test override for jolly-roger/no-sync-mongo-methods is in `imports/server/accounts.ts`, for generating email templates, which still has to be synchronous)
=> Remove last users of MeteorPromise

imports/lib/models/Model.ts, tests/unit/imports/server/Model.ts
Even if a schema has a default, we still need to relax the inner type to make sure we handle arrays correctly.
=> Fix modifiers for arrays with defaults

imports/lib/models/Documents.ts, imports/lib/models/Model.ts
This ensures that we attach the schemas in production like we expect. And while we're in the area, make Documents a SoftDeletedModel.
=> Actually add models to AllModels

imports/server/discord.ts, imports/server/discordClientRefresher.ts, imports/server/migrations/49-schema-fixups.ts, imports/server/migrations/all.ts
When we migrated the database to support multiple answers, we never actually removed the old (singular) answer property. Additionally, the Discord API returns "null" for avatar when the user has no avatar, but we marked the field as optional (meaning it can be absent, but if present, must be a string).
Add a migration to fix both of those (and logic to handle the avatar properly going forward).
=> Fixup issues discovered by schema validation

.eslintrc.json, eslint/index.ts, eslint/rules/no-disallowed-sync-methods.ts, imports/server/accounts.ts, tests/unit/imports/server/generateJsonSchema.ts
As Meteor continues to introduce more async alternatives to synchronous methods, we will want to be able to ban more than just Mongo-specific methods, so make the rule a bit more generic.
(As an example, there's now an `Email.sendAsync` which we should ideally be using instead of `Email.send`, although it's not currently in the TypeScript type declarations)
=> Refactor async lint rule

imports/client/components/NotificationCenter.tsx, imports/lib/isAdmin.ts, imports/lib/permission_stubs.ts, imports/server/publications/pendingGuessesForSelf.ts, tests/acceptance/profiles.tsx
By changing our permission stubs to accept the relevant partials of users and hunts, we can take advantage of those stubs in places where we don't have complete objects, such as pendingGuessesForSelf, where we're not guaranteed to see a full object (but where any update _will_ have the data we need to use the stub functions).
(This came up while I was doing some unrelated experimentation, but I think it's a good improvement independent of that)
=> Use permission stubs to simplify pendingGuessesForSelf

client/stylesheets/_theme.scss, imports/client/components/AnnouncementToast.tsx, imports/client/components/AnnouncementsPage.tsx, imports/client/components/NotificationCenter.tsx
`AnnouncementPage` was hastily constructed in a different age.  Let's bring it a bit more up-to-date by:
* Extracting a Toast-based component to use for announcements in both the NotificationCenter and on the AnnoucementPage
* Showing a rendered preview of the announcement, which will probably help people with getting the markdown link test/url order correct more often when posting links
* Sorting messages from most recent to oldest, since more recent messages are likely more important for users to read than older ones.
Fixes #1358.
Before:
https://user-images.githubusercontent.com/307325/216796301-3aabbde9-e58e-4fa1-9fc5-a8d1d23de79b.mov
After:
https://user-images.githubusercontent.com/307325/216796307-27fb36f6-c7ea-4217-a977-a745ef9ea2a6.mov
=> Rewrite AnnouncementPage to preview and reuse Toast

cloudformation/jolly-roger.yaml
When a new Jolly Roger container is being picked up by watchtower, we temporarily have no running Jolly Roger container, which causes nginx to return a (fairly unhelpful) 502 error. We can make the experience better by serving a custom 502 page informing users of what is going on and automatically refreshing the page once the container is back up.
Fixes #1362.
As per usual with CloudFormation changes, I've already deployed this to prod to validate that it behaved correctly. Here's a screen capture from testing it (which I did by running `sudo docker stop jolly-roger` and then `sudo docker start jolly-roger`):
https://user-images.githubusercontent.com/28167/216797161-7ff7710d-9b8f-4489-92a1-b331526514cf.mov
=> Add a custom 502 page to nginx config

imports/server/getOrCreateTagByName.ts, imports/server/methods/addPuzzleTag.ts, imports/server/methods/createPuzzle.ts, imports/server/methods/updatePuzzle.ts
It looks like we used to return a pseudo-Tag-object, but none of the callers actually care about that anymore.
(Noticed this while playing with the branded types branch)
=> Change return type for getOrCreateTagByName

imports/server/garbage-collection.ts, imports/server/mediasoup.ts
Mediasoup's default configuration attempts to make SCTP delivery ordered and reliable. However, for our heartbeat system, which sends a new message every 100ms, that's not actually what we want - if one heartbeat gets dropped, we don't want to wait for retransmission of that heartbeat before delivering subsequent ones to the receiving application.
Setting ordered: false will allow packets to be delivered out of order, and setting maxRetransmits: 1 should allow the sending side to be more aggressive about dropping missed packets, instead of trying to retransmit them.
=> Make heartbeats less reliable and hopefully more robust

imports/lib/models/Model.ts
Meteor's find method has the slightly confusing property that passing an `undefined` query explicitly behaves differently than passing no query (since the query is an optional parameter). Passing `undefined` explicitly returns an empty result set.
We want to allow the query to be optional, as with Meteor, but that resulted in us explicitly passing undefined to Meteor, which caused the empty result set behavior. So instead make sure we pass an empty query. (This means that we can no longer access the explicit-undefined behavior from Model, but I don't think we've ever wanted that anyway.)
=> Fix find with no arguments

imports/Flags.ts, tests/main.ts, tests/unit/imports/server/Flags.ts
Bug fix from #1448.
If the flag record does not exist by the time we initialize our observer, then that means that state is undefined, but the new state implied by calling checkUpdate would also be undefined, so we'd never call the callback. We don't actually want to checkUpdate; we want to call the callback manually.
(For the record, this currently breaks the startup of any of our server-side stuff that's using `observeChanges`, including at minimum calls and probably some other stuff like Discord and Drive activity)
=> Fix initial firing on Flags.observeChanges

.eslintrc.json, imports/client/components/CallSection.tsx, imports/client/components/HuntListPage.tsx, imports/client/components/ModalForm.tsx, imports/client/components/ProfileList.tsx, imports/client/components/PuzzleDeleteModal.tsx, imports/client/components/PuzzlePage.tsx
React's new-ish createPortal allows you to place a component outside of its rendering tree, which makes sense for modals which are effectively untethered from where they would appear by default in the DOM.
This is a more stable fix for problems we've had in the past with, e.g., overlay triggers, where the modal is inside of the overlay trigger and thus triggers the tooltip.
For some reason, the structural changes to the components which used forwardRef caused the react/prop-types eslint rule to start complaining. Since it's not really useful in a TypeScript world, I just turned it off.
Fixes #1317.
=> Use createPortal for modal popups

imports/lib/models/Model.ts, imports/lib/models/SoftDeletedModel.ts, imports/lib/models/withCommon.ts, imports/lib/models/withTimestamps.ts, imports/lib/models/withUsers.ts, package-lock.json, package.json
zod added an additional type constraint on the shape of a `ZodObject` and moved the `extendShape` helper around, so we need to update to match.
Supersedes #1515
=> Take zod update

.github/dependabot.yml
Dependabot has support for grouping updates based on various characteristics. Given that most package updates either require no code changes or are backwards-incompatible and should be ignored, we can reduce PR churn by opening a single PR with all pending changes.
In order to make this more effective, also push updates to happen weekly, instead of daily. I picked Fridays, as that tends to be when I'm most available to look at PRs, and leads into the weekend for maximum flexibility.
Note that none of this applies to security updates, which dependabot will still open immediately.
(Documentation for these configuration options is at https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file. That page also includes the …
=> Coalesce dependabot updates

.github/dependabot.yml
This both gives us better persistent tracking of updates that we intentionally aren't taking and also gives us a workaround for a current bug where the "@dependabot ignore" directive doesn't work for "@"-prefixed packages.
Once merged, I'll go through and issue unignore directives for each of these, so that they don't override the ignore directives in the config file.
(As a note, I have filed a bug with GH about the error in the @dependabot directives and they've acknowledged that they're working on it. This still seems like a better approach, though)
=> Configure dependabot ignores by file

package-lock.json, package.json
styled-components v6 is written in TypeScript, so we no longer need a separate type package.
=> Drop @types/styled-components

.github/dependabot.yml
In practice, we're seeing too many cases where a small number of incompatible updates blocks all other updates from going through, meaning that the end result is we're just not taking updates in a timely manner.
=> Switch back to ungrouped dependabot updates

imports/client/components/NotificationCenter.tsx, imports/client/components/Puzzle.tsx, imports/client/components/PuzzleList.tsx, imports/client/components/PuzzleListPage.tsx, imports/client/components/PuzzlePage.tsx, imports/client/components/RelatedPuzzleGroup.tsx, imports/client/components/RelatedPuzzleList.tsx, imports/lib/models/BookmarkNotifications.ts, imports/lib/models/Bookmarks.ts, imports/lib/models/facade.ts, imports/lib/publications/bookmarkNotificationsForSelf.ts, imports/methods/bookmarkPuzzle.ts, imports/methods/dismissBookmarkNotification.ts, imports/server/GlobalHooks.ts, imports/server/hooks/BookmarkNotificationHooks.ts, imports/server/methods/bookmarkPuzzle.ts, imports/server/methods/dismissBookmarkNotification.ts, imports/server/methods/index.ts, imports/server/publications/bookmarkNotificationsForSelf.ts, imports/server/publications/index.ts, imports/server/publications/puzzleForPuzzlePage.ts, imports/server/publications/puzzlesForPuzzleList.ts, package-lock.json, package.json
Some of our team members have asked for a way to more easily keep track of puzzles they care about, even when they're not currently looking at them.
Bookmarked puzzles are shown in a section at the top of the puzzle list page (in addition to showing up in their normal place in the list):
When a puzzle is solved, users that have that puzzle bookmarked get a notification:
One thing that's missing right now is a UI element on the individual puzzle page for bookmarking a puzzle, as I'm not entirely sure where to put it.
@Apophenia I'm curious if this seems like it would work for your use case, since you were one of the people who requested this.
Fixes #1368.
=> Add bookmarking for puzzles

imports/client/components/Avatar.tsx, imports/client/components/CallSection.tsx, imports/client/components/ChatPeople.tsx, imports/client/components/FancyEditor.tsx, imports/client/components/NotificationCenter.tsx, imports/client/components/Puzzle.tsx, imports/client/components/PuzzleAnswer.tsx, imports/client/components/PuzzlePage.tsx, imports/client/components/PuzzleTable.tsx, imports/client/components/RTCDebugPage.tsx, imports/client/components/SetupPage.tsx, imports/client/components/Tag.tsx, imports/client/components/styling/PeopleComponents.tsx
By default, styled-components will pass on whatever props you pass a styled component on to the underlying component.  In the cases where we're specifying props to adjust the styling, we don't actually want those props to be propagated, since e.g. `<div>` doesn't know what to do with a `isAdministrivia` property being set on it.
Since this is a common use case, styled-components has multiple mechanisms for controlling propagation of props, but the tersest and most immediately legible is that it treats props that start with a `$` as "transient props", and will not propagate any of them.
We should prefer transient props any time we are passing props to a `styled()` component purely for the purpose of controlling the styles applied.
This should remove a large volume of warnings and errors in …
=> Use transient props to styled-components

cloudformation/jolly-roger.yaml
For some reason, when left in the default TCP mode, haproxy was leaking connections to the backend HTTP/1 nginx service. Explicitly configuring that backend as an HTTP backend seems to fix the issue. This doesn't seem to happen with either the TURN or HTTP/2 backends.
=> Explicitly configure tcp/http modes on haproxy

imports/client/components/BookmarkButton.tsx, imports/client/components/Puzzle.tsx, imports/client/components/PuzzlePage.tsx, types/react.d.ts
https://github.com/deathandmayhem/jolly-roger/assets/28167/b0e3cf0f-509a-4d76-bc2c-ffb39b5e230b
=> Add a small bounce when bookmarking a puzzle

imports/lib/models/mediasoup/ProducerClients.ts, imports/lib/models/mediasoup/ProducerServers.ts
We assumed these would always be UUIDs, but it seems like at least modern Firefox returns track IDs that are not (pure) UUIDs. (They seem to have curly braces around them).
Since we just use the track ID to connect the ProducerClient and ProducerServer records, we need them to be present, but we can treat them as opaque.
cc @egnor (Thanks for the bug report!)
=> Allow track IDs to be opaque strings

imports/client/components/FancyEditor.tsx, imports/client/components/OthersProfilePage.tsx, imports/client/components/OwnProfilePage.tsx, imports/client/components/ProfileList.tsx, imports/lib/discord.ts
It looks like we still see a mix of Discord account references that both have and lack discriminators. At some point in the future once all usernames have been migrated, we may no longer need to track the discriminator at all, but for the time being only display it if it represents a non-migrated value (i.e. is not "0").
Before:
After:
=> Fix rendering of post-username migration Discord handles

imports/server/gdriveActivityFetcher.ts
We see intermittent failures hitting the Google Drive Activity API, but we should not let the fetcher loop die when that happens.
(Easier to review with a word-diff)
Fixes #1953.
=> Catch activity fetch failures and retry

imports/client/components/HuntApp.tsx, imports/client/components/HuntEditPage.tsx, imports/lib/models/Hunts.ts, imports/lib/models/User.ts, imports/methods/acceptUserHuntTerms.ts, imports/server/methods/acceptUserHuntTerms.ts, imports/server/methods/index.ts, imports/server/users.ts
This is a way to surface rules of engagement for a hunt and require hunters to agree to them before interacting with the hunt.
Here's what it looks like:
The modal is pretty aggressively blocking - there's no way to interact with background elements without clicking the "agree" button. Once you agree, that state is stored on your user object.
There's also a preview button on the hunt edit page that you can use to preview the rendering. (We should plausibly go back and add something similar to the signup message field)
=> Add per-hunt "terms of use"

cloudformation/jolly-roger.yaml
We need to specify an AWS region. We will immediately query for the actual region of the S3 bucket we're interacting with, but we still need this first. Additionally, we need the s3:GetBucketLocation and s3:ListBucket permissions in order to do this.
=> Fix CloudFormation config for S3 image uploads

imports/client/components/Avatar.tsx, imports/client/components/CallSection.tsx, imports/client/components/ChatPeople.tsx, imports/client/components/Spectrum.tsx, imports/client/components/styling/PeopleComponents.tsx
- Background color is peachy instead of pink
- Border and blue glow on "self" box
- Initial letter is bold
- Tweaks to mute/deafen icons/colors/sizes
- Fix weird alignment of volume bars
This is on top of @ebroder 's prettier branch so there's a bunch of changes associated with that (or prettier auto-fixes in the files I touched >.<). I could go through it by hand after the fact to take those out but I wanted to get this pushed up already :P
=> Audio call styling changes

imports/client/components/AllProfileListPage.tsx, imports/client/components/HuntProfileListPage.tsx, imports/client/components/HuntersApp.tsx, imports/client/components/ProfileList.tsx, imports/client/components/ProfilePage.tsx, imports/client/components/Routes.tsx, imports/client/components/UsersApp.tsx
Historically, we've only had a single route for viewing a user profile under `/users`, but that meant that breadcrumbs broke when you went from a hunt-specific profile list to an individual profile.
This mounts the profile view under both `/users/:userId` and `/hunts/:huntId/hunters/:userId` and makes sure that breadcrumbs behave correctly regardless of how you get there.
🎁 @flipdog
=> Fix breadcrumbs when looking at a profile from a hunt

cloudformation/jolly-roger.yaml
The biggest improvement seems to have come from pinning the older version of haproxy, as I think that 2.9.1 has some sort of issue, at least with our configuration. While I was debugging, I went and enabled some additional timeouts to make sure we were GCing connections successfully - even if those weren't the proximate issue, they still seem useful to prevent resource leaks.
=> Try to fix haproxy config again

.github/problem-matchers/eslint.json, .github/problem-matchers/stylelint.json, .github/problem-matchers/tsc.json, .github/workflows/build.yml, Dockerfile, package-lock.json, package.json
Fix presentation of lint failures as GitHub annotations, originally introduced in #725 and broken (I think) in #1197.
For background, GitHub's annotation extraction requires that file paths be absolute and reflect the working directory that the repository is checked out into. That doesn't work great for us because we do our builds inside of a Docker container under a different path. So we need to rewrite file paths in the outputs that we get from running lint inside Docker. We do that using a Docker argument (i.e. environment variable) that gets passed in. Previously, we needed to escape our use of that variable in the lint script so that Docker itself wouldn't apply variable substitution that we didn't want, but with new style heredocs, Docker wasn't applying those substitutions anymore. …
=> Rework how we extract lint failures into GitHub annotations

docs/assets.md, package-lock.json, package.json, tests/check_docs.mts
Some higher-level information about a codebase are hard to document inline in code. For systems that span multiple files, functions, etc., it's useful to have a more centralized source of documentation. However, the inherent risk of any such centralized documentation is that it quickly becomes out of date.
Introduce a `docs` folder, containing such higher-level documentation. However, to mitigate against docs becoming out of date, additionally introduce some validation in the form of a new, homegrown linter. This linter requires that some metadata be included with each documentation file: specifically, which files the documentation covers and when the documentation was last updated. If the files are ever updated without a corresponding update to the docs, the linter will fail.
Here's what …
=> Add a semi-simple documentation system

imports/server/gdriveActivityFetcher.ts
If we're using a root folder, then we should pass that along when fetching Drive activity. This is especially important if the folder in question isn't inside the Drive of the user that's fetching activity data (e.g. if it was created elsewhere and shared to the user).
Fixes #1964
=> Specify root folder if present for activity fetch

imports/client/components/App.tsx, imports/client/components/HuntNav.tsx, imports/client/components/PuzzleListPage.tsx
I can never ever see the blue items menu (hunt website + JR utility links) even when looking for it:
- partly because it's not in an expected place for navigation,
- partly because it gets stretched super wide on non-small windows such that it doesn't even look like a set of buttons.
Now they're in the nav bar (if a hunt ID is set; they don't appear on the hunts index page).
This also improves contrast on the top nav bg a little and adds a bottom border to the nav bar (in the same color as the vertical panes separator).
In small windows the menu appears in the old spot and looks more or less like the old one. Not idea having it move, but I'm still trying to decide whether to have multiple dropdown menus in the nav on the smallest screens or something else. Definitely more fiddling …
=> Move JR nav items into top nav bar

cloudformation/jolly-roger.yaml, imports/server/mediasoup.ts
MIT's network is documented to allow UDP connections on ports 50000+. By moving mediasoup into that port range, we can hopefully avoid needing a TURN relay on this network.
The deployment of these two changes will be a bit messy, as they can't be pushed out atomically with each other. That should be fine as long as they deploy when Jolly Roger isn't being heavily used.
=> Swap port allocations between mediasoup and coturn

imports/client/components/App.tsx, imports/client/components/GuessQueuePage.tsx, imports/client/components/styling/FixedLayout.tsx
The always-visible topbar is actually not the best use of space on most pages:
* the topbar is easily found by scrolling back to the top of the page
* not having it take up 50 pixels of vertical space means 50 more rows for more-useful content like the puzzle list or guess queue
* having the top bar scroll away means we don't have to worry as much about having it be strongly-contrasting in color with other content that would slide under the fixed navbar.
* while some SPAs do have a more fixed layout, most other websites that have a navbar like this either do not make it sticky at all, or at least hide it when scrolling down
So let's just make the topbar be scrollable like most of the rest of the web, and give a little more space for content.
The view on `PuzzlePage` will not change at …
=> Allow top navbar to be scrolled away on most pages

cloudformation/jolly-roger.yaml
Our haproxy issues seem to have been caused by a bug in the most recent haproxy release, while these new timeouts have some drawbacks around how they interact with long-held subscriptions.
=> Revert some new haproxy timeouts

.github/dependabot.yml
We've seen some cases - e.g. #1997 and #1999 - where two different packages are sufficiently co-dependent that they can't be updated independently. Fortunately, this is easy to express in dependabot config.
This should be better than our attempts at an "all" group by virtue of being a bit more limited
=> Group together updates that need to be taken together

cloudformation/jolly-roger.yaml
Custom metrics are fairly expensive, and we shouldn't bother paying for them year round.
(Note that we still get CPU metrics and anything else that the hypervisor is able to observe from the outside, and I believe those are free)
=> Allow disabling CloudWatch agent

imports/server/publications/chatMessagesForFirehose.ts
This is one of our most database-intensive pages, and there's no reason to blow up the amount of server-side work we have to do to support it.
=> Don't use publishJoinedQuery for firehose

cloudformation/jolly-roger.yaml
We add a parameter to specify a CSV of the users and their SSH keys, and we use a lambda function to convert it into the "users:" stanza for the EC2 config.
An alternative could be to specify two parallel parameters, one for the usernames, and one for the SSH keys. We could then use the AWS::LanguageExtensions function Fn::ForEach to loop over one list while using Fn::Select to pull the corresponding object from the other list. This would simplify the implementation, but make the "API" (the parameters) arguably more complex.
Fixes #2013
=> Make SSH user list configurable in CloudFormation config.

cloudformation/jolly-roger.yaml
If this parameter is false (to turn off serving), we only keep around static entities - e.g. roles, instance functions, and the S3 bucket for image uploads. This allows us to more easily flip serving off and on without having to fully delete the stack, which has side effects like deleting the S3 bucket and requiring reentry of all parameters on recreation.
=> Provide a CloudFormation parameter allowing stack shutdown.

cloudformation/jolly-roger.yaml, package-lock.json, package.json, scripts/run_jolly_roger.sh
- Use a fixed name for the role used to run EC2 instances so it can be referenced in the MongoDB config. Note that if you try to set up JR instances across multiple regions, it will now fail due to the role name being duplicated. If this is a concern, we could append the region name to the role (but this would require one user per region in MongoDB).
- Include aws4 in dependencies as required for AWS authentication.
=> Enable AWS IAM authentication with MongoDB.

.github/dependabot.yml
v15 dropped support for Node 14 (and introduced usage of the `&&=` operator, which is explicitly unsupported).
=> Pin @testing-library/react to below v15

imports/client/components/NotificationCenter.tsx
These interact quite badly if they reference a deleted Hunt object, which is exactly the situation you wind up in if you simply create the sample hunt and then delete it.
Fixes #2100.
=> Avoid using non-null assertions in NotificationCenter

Dockerfile, cloudformation/jolly-roger.yaml, scripts/run_jolly_roger.sh
credstash has gone a bit stale, and it requires a customer-managed KMS key which costs $1/month. We can use SSM instead which has zero/much lower costs and is overall easier to manage.
See #2117
=> Move from credstash to AWS Systems Manager Parameter Store.

cloudformation/jolly-roger.yaml
UserData is bumping up near the 16K limit; this gives a bit more breathing room.
=> Switch from hardcoded key to keyid for Ubuntu docker apt source.

imports/server/accounts.ts
I don't believe this constitutes a security issue, because `Google.retrieveCredential` validates that `key` is a string before issuing any database queries, and the key is long and random. It may technically be possible (if you get your hand on a key) to swipe someone else's pending login by passing `secret: {"$ne": null}` or similar.
I think this is largely a case of "if you have root, it's easy to get root", but it seems like good practice to clean it up anyway.
=> Verify type of key/secret for Google logins

cloudformation/jolly-roger.yaml
This mode differs as follows:
- The EC2 job is now responsible for terminating TLS. It uses certbot to request Let's Encrypt certificates on startup and renews them in a daily cron job. We use haproxy's stats socket to update the certificate in the running instance without needing to restart it.
- We request an elastic IP and point DNS to it. Whenever the ASG launches a new instance, we run a lambda to associate the elastic IP with the new instance (and disassociate it from any prior instance).
Note: Let's Encrypt limits you to 5 new certificate requests per week - see https://letsencrypt.org/docs/duplicate-certificate-limit/. Since we aren't saving/restoring the configuration data between instances, it's possible to hit this limit when testing deployment changes or making frequent …
=> Add the ability to disable load balancing to CloudFormation config.

imports/client/components/AccountForm.tsx
The URL seems to be considered relative from some prior path in history, e.g. going to /join/ABC ends up looking for /join/google-signin.svg even though we're first redirected to /login. Use an absolute path instead.
=> Fix potential failure loading Sign in with Google button.

cloudformation/jolly-roger.yaml
There have been some bugfixes since 2.9.1 which was apparently leaking connections when 2.9.0 was not. It's unclear to me if this has been fixed, but my instance has run for a few days and has no open connections:
```
$ echo "show info" | sudo socat stdio /var/run/haproxy/stats.sock  | grep Conns 
CurrConns: 0
CumConns: 893
MaxSslConns: 0
CurrSslConns: 0
CumSslConns: 876
```
And I have seen sporadic load failures and at least one segfault in the logs with the pinned version, so it seems like we should try unpinning the version.
=> Unpin haproxy version.

imports/server/publications/pendingGuessesForSelf.ts
This bug appears to have been introduced in
518dc82235528ebfd1834fca6dd64a9ccfb20d52.  It appears that the only effect would have been that if an operator for a hunt was demoted, clients connected before the demotion would continue to see pending guesses for that hunt.
I found this via manual inspection of the source file when I was experimenting with trying to make use of Meteor 2.16's `observeChangesAsync` and `observeAsync`.
=> Fix missing function invocation in pendingGuessesForSelf

imports/client/components/DocumentDisplay.tsx
For some reason, when a Sheets URL is loaded with ?...#gid=0, it redirects to ?...&gid=0#gid=0; this redirect puts a spurious entry in the navigation history, which breaks the first back button press. Embedding the final URL fixes the back button.
Fixes #2162
=> Fix browser back on puzzle pages.

cloudformation/jolly-roger.yaml
In this mode, only memory and swap usage is captured. At two metrics per instance, this usage should remain in the free tier (10 custom metrics total). Total CPU usage is available as a built-in metric in EC2, so this should give a reasonable picture of CPU/memory usage for basic monitoring.
The additional metrics around detailed CPU, disk, and network are available in the "detailed" mode (the default).
This also fixes an issue with the indentation in the YAML when CloudWatch is enabled. We also have to be careful when creating the CloudWatch JSON config via string substitution, which unfortunately makes for a somewhat cludgier YAML file.
See #2117
=> Enable a "minimal" mode for CloudWatch monitoring.

imports/server/googleClientRefresher.ts, package-lock.json, package.json
The default retry policy (documented
[here](https://github.com/googleapis/gaxios/#request-options)) does not retry POST requests. But most Google API calls use POST requests under the covers, including read-only APIs like [Drive
Activity](https://developers.google.com/drive/activity/v2/reference/rest/v2/activity/query). So we can also ask to retry POST requests.
We retain other aspects of the default policy, such as the number of attempts (3) and the HTTP status codes to retry (100-109, 408, 429, 5xx). If a request succeeds on a retry, the failure is kept silent and does not pollute the logs.
The main risk is that a POST method might mutate some state despite returning a failure, and that inline retries might handle that incorrectly or otherwise make things worse than retrying the full …
=> Retry more Google API failures.

Dockerfile
The attempt to pin a specific version of the meteor tool never actually worked, which means the build broke once Meteor 3.0 was officially released.
=> Fix the build.

imports/client/components/PuzzleListPage.tsx, imports/client/components/PuzzleModalForm.tsx
=> Reset puzzle modal form upon successful submission.

imports/client/components/PuzzleListPage.tsx
As best as I can tell, this was a typo. Regular puzzle groups have their state stored as long as there is no active search query. This makes sense - as commit 2e09393894024aa7c44a7b2ddac106d656ba6140 notes, it would cause confusion when searching if we paid attention to collapse state when showing search results. However, the deleted group behaves the _opposite_ way - the state is _only_ persisted during searching. I can't imagine why persisting the state in this case would be desirable, but not during the no-search case. So this change makes everything consistent.
See #2278
=> Properly store deleted puzzle group collapse state.

Dockerfile, eslint/package.json, imports/client/hooks/persisted-state.ts, package-lock.json, package.json
Pretty straightforward drop-in replacement of the old library with the new one.  The data storage format is the same, so we shouldn't lose any existing saved state.
=> Replace use-persisted-state with usehooks-ts

imports/client/components/PuzzlePage.tsx
These guardrails exist for guess-queue mode but were missing from no-guess-queue mode. This change brings parity between the two modes.
Note that:
1. This is not a firm guarantee against (unintended) duplicate answers, since two submissions made at ~the same time won't detect the presence of the other submission in time. Only a read-modify-write transaction would prevent this.
2. If duplicate answers _are_ submitted, clearing one answer in no-guess-queue mode will mark the puzzle as incorrect and clear the answer, while leaving a correct guess in place. This is an inconsistent state. The workaround is to clear all copies of the answer and resubmit it.
See #2276
=> Add guardrails for duplicate/excess answers in no-guess-queue mode.

imports/client/components/DocumentDisplay.tsx, imports/client/components/PuzzlePage.tsx
This would hopefully have no effect if the user isn't logged into their
linked account (it would redirect to the default account, as before),
but would select the linked account if available, which could prevent
users from showing up anonymously.
Depends on #2312 for merge conflict reasons, but could be refactored independently if desired.
=> Attempt to use linked Google account when loading documents.

imports/client/components/GuessQueuePage.tsx, imports/client/components/HuntNav.tsx, imports/client/components/NotificationCenter.tsx
- Disable guess notifications
- Hide extraneous columns from the guess queue page
- Rename "Guess queue" to "Answer log" and "Guesses" to "Answers"
Fixes #2168
=> Hide more guess queue functionality when queue is disabled.

imports/lib/models/Settings.ts, imports/server/gdriveActivityFetcher.ts, imports/server/methods/configureGdriveCreds.ts
It appears that the drive API counts various actions taken by the server account in the process of creating a new document for a puzzle as edits (in that the edit field is populated). This is confusing as it looks like there is drive activity in every new puzzle when it is first created, even if nobody has opened it or edited the document.
We can filter out events associated with the ID of the server account to prevent this confusion. Given that this account is recommended to not be one used for actual hunting, this seems like a reasonable approach.
We were not previously storing the ID when logging into a server account. We store it for future sign-ins, but for simplicity, do not bother with backfill. This means that until the server admin signs in again, they will continue to see …
=> Exclude Drive Activity from the server's Google account.

imports/client/components/InsertImageModal.tsx, imports/server/methods/insertDocumentImage.ts
The Google App Script insertImage API only appears to support GIF/PNG/JPG images. Attempts to upload other formats (e.g. webp) fail with an internal error.
For uploads, indicate that these are the only accepted file extensions. Clients often treat this as a suggestion rather than a hard requirement if someone is particularly certain that a file will work despite the extension being different.
For links, make a HEAD request for the image and inspect the Content-Type in the response headers. Fail open in cases where we can't definitively determine the Content-Type.
Note that copy-pasting images via the keyboard shortcut works and supports other formats, so this is probably a simpler approach to take in most cases.
See #2285
=> Improve validation for image uploads.

cloudformation/jolly-roger.yaml
v18 is slated to be deprecated on 9/1 and it will become impossible to create new lambda functions with it on 10/1.
Tested by turning down and turning up stack and verifying lambdas executed successfully. SshUsers wasn't triggering properly; as a workaround, added a condition to only create the function/output when serving is on (since the output is only needed by the EC2 template), which ensures it is triggered upon turning serving off and on.
=> Update CF Lambdas from NodeJS v18 to v22.

imports/lib/models/APIKeys.ts, imports/lib/models/Model.ts, imports/server/indexes.ts
The second commit is the actual motivation for this PR: we want `APIKeys` to have a unique index on `key`.
The first commit is what makes that change possible without Mongo throwing an error: Mongo will reject attempts to create two indexes with the same name and different options, as well as two indexes with the same structure and options and different names.  To allow the appearance of "in-place" index changes, we need slightly more clever logic around dropping and creating indexes.
To achieve that, we add a `name` field to our `ModelIndexSpecification`, generate the same `name` Mongo would by default, and then teach `imports/server/indexes.ts` to notice when a requested index would conflict with an existing one, and drop conflicting indexes first before adding new ones.  This results …
=> Drop conflicting indexes first before adding new indexes

.github/dependabot.yml, imports/server/mediasoup.ts, package-lock.json, package.json
Split into a package update commit and a "the things I did to make the lints pass and the code run".
Tested only the `isDevelopment` local addressing codepath at present.  I don't have a particularly convenient way to test the "using a public IP" codepath short of "deploy it fully and try it out" (which I'm happy to do on merge), and I definitely have not tried the backend-to-backend forwarding, but ~none of the meaningful code there changed on our end as far as I know.
My intuition on protocol support is that we want to support both UDP and TCP for client-to-server connections (as UDP is generally better for low latency, but TCP is sometimes needed for TURN or other fallback paths), and that we would likely prefer UDP for server-to-server connections (since we control the networking on …
=> Update mediasoup to 3.19.2
