deathandmayhem/jolly-roger

imports/client/components/HuntListPage.jsx
imports/client/components/NotificationCenter.jsx
imports/client/components/Puzzle.jsx
imports/client/components/PuzzlePage.jsx
imports/client/components/RelatedPuzzleGroup.jsx
imports/client/components/TagList.jsx
package-lock.json
package.json
public/bootstrap.min.css.map
public/fonts/glyphicons-halflings-regular.eot
public/fonts/glyphicons-halflings-regular.svg
public/fonts/glyphicons-halflings-regular.ttf
public/fonts/glyphicons-halflings-regular.woff
public/fonts/glyphicons-halflings-regular.woff2

The Font Awesome React component renders icons using SVG, which means
that we don't have to worry about font paths anymore. Also the icon set
is pretty great.
(This supersedes #165)

Switch from emoji and Glyphicons to Font Awesome

---

imports/client/components/App.jsx
imports/server/guesses.js
imports/server/hooks/slack-hooks.js

Some TODO lines are vestigial -- either we've implemented the thing named or it's no longer relevant to current designs.

Remove obsolete TODOs

---

imports/client/components/GuessQueuePage.jsx
imports/client/components/HuntListPage.jsx
imports/client/components/Puzzle.jsx
imports/client/components/PuzzleListPage.jsx
imports/client/components/PuzzleModalForm.jsx
imports/client/components/PuzzlePage.jsx
imports/client/components/SplitPanePlus.jsx

Switch from callback refs to React.createRef API

---

imports/client/components/NotificationCenter.jsx

This is what's left of #196 after #199 landed

Add breaking whitespace in guess queue announcements

---

imports/client/components/UserInvitePage.jsx

Disable form while invite call is in flight

---

imports/client/components/PuzzlePage.jsx

Don't show edit puzzle buttons in related puzzle pane

---

imports/client/components/PuzzlePage.jsx

This can save screen real estate by avoiding showing tons and tons of lines
with display names and timestamps when they're the same person talking a lot.
I want to show sender + timestamp if the senders differ (for correctness) or if
the timestamps differ by more than, say, 60 seconds.  This strategy is not
particularly sophisticated; I could imagine fancier rules for when we suppress
showing senders like tracking the time of the last-timestamp-shown message and
seeing if that has gotten large enough, but that's unlikely to matter a lot
unless people primarily talk entirely to themselves in chat.
This could get a little computationally expensive in the event we have to
reparse many dates for puzzles with very long chat histories where the same
person writes a lot of messages in a row.  I …

Suppress sender in chat if same as previous message and sent in same minute

---

imports/client/components/PuzzleListPage.jsx

It's not actually slashes that are the problem.

Make searching for tags case-insensitive

---

package-lock.json
package.json

Only thing worrisome in here is the marked update, but I confirmed that our monkeypatching still works.

Pick up some security fixes

---

.eslintrc
client/main.ts
client/stylesheets/breadcrumbs.scss
imports/client/close.ts
imports/client/components/AccountForm.tsx
imports/client/components/AnnouncementsPage.tsx
imports/client/components/App.tsx
imports/client/components/Authenticator.tsx
imports/client/components/DeepLink.tsx
imports/client/components/Documents.tsx
imports/client/components/HuntApp.tsx
imports/client/components/HuntListPage.tsx
imports/client/components/NotificationCenter.tsx
imports/client/components/ProfilePage.tsx
imports/client/components/Puzzle.tsx
imports/client/components/PuzzleListPage.tsx
imports/client/components/PuzzleModalForm.tsx
imports/client/components/PuzzlePage.tsx
imports/client/components/Routes.tsx
imports/client/components/SetupPage.tsx
imports/client/components/SplitPanePlus.tsx
imports/client/main.tsx
imports/client/marked.ts
imports/lib/models/base.ts
package-lock.json
package.json

(Except for the honeycomb integration code - that reaches into a bunch
of Meteor guts and doesn't seem like it would benefit from writing a
bunch of ambient type declarations just to make it compile.)

Convert everything to Typescript

---

imports/client/components/AccountForm.tsx
imports/client/components/App.tsx
imports/client/components/Authenticator.tsx
imports/client/components/CelebrationCenter.tsx
imports/client/components/HuntApp.tsx
imports/client/components/HuntListPage.tsx
imports/client/components/NotificationCenter.tsx
imports/client/components/ProfilePage.tsx
imports/client/components/Puzzle.tsx
imports/client/components/PuzzlePage.tsx
imports/client/components/SetupPage.tsx
imports/client/components/TagEditor.tsx
imports/client/components/TagList.tsx
imports/lib/models/base.ts
imports/lib/models/hunts.ts
imports/model-helpers.ts
imports/server/api/resources/users.ts
imports/server/api_keys.ts
imports/server/chat.ts
imports/server/guesses.ts
imports/server/hooks/slack-hooks.ts
imports/server/hunts.ts
imports/server/profile.ts
imports/server/puzzle.ts
imports/server/users.ts
package-lock.json
package.json

findOne isn't guaranteed to find a result; it might return undefined.
However, the DefinitelyTyped declaration for findOne doesn't contemplate
this, which results in a couple of potential bugs.

Monkeypatch type of findOne to return undefined

---

imports/client/components/HuntApp.tsx
imports/client/components/HuntProfileListPage.tsx
imports/client/components/ProfilePage.tsx
imports/client/components/PuzzlePage.tsx

Its type annotation is quite non-specific, which means that it can
easily cover up other issues.

Stop using _.compose

---

imports/client/components/PuzzleModalForm.tsx
imports/lib/schemas/puzzles.ts
imports/lib/schemas/typedSchemas.ts
imports/server/puzzle.ts

Also fix the typing of `autoValue` vis-a-vis arrays: the behavior of the actual
call is to call the method once for each value in the array, not once for the
whole array.

Add support for creating/modifying expected answer count

---

imports/client/components/DeepLink.tsx
imports/client/components/NotificationCenter.tsx
imports/client/components/ProfileList.tsx
imports/client/components/Puzzle.tsx
imports/client/components/PuzzleListPage.tsx
imports/client/components/PuzzleModalForm.tsx
imports/client/components/PuzzlePage.tsx
imports/client/components/RelatedPuzzleGroups.tsx
imports/client/components/TagEditor.tsx
imports/lib/models/base.ts
imports/lib/models/hunts.ts
imports/lib/models/pending_announcements.ts
imports/lib/models/puzzles.ts
imports/model-helpers.ts
imports/server/accounts.ts
imports/server/gdrive.ts
imports/server/hunts.ts
imports/server/observability.js
imports/server/puzzle.ts
imports/server/subscribers.ts

Reverts deathandmayhem/jolly-roger#279

Revert "Replace lots of underscore with native equivalents"

---

imports/client/components/GuessQueuePage.tsx

This makes it possible to filter down from a hunt's worth of submissions to
particular puzzles or guesses.  Of course ctrl-f worked before, but this makes
it easy to scan over guesses.

Add search bar to guess queue page

---

build.sh
package-lock.json
package.json

`meteor npm install --save bcrypt@latest` for the package changes
Manual repo change for the `build.sh` change per https://github.com/nodesource/distributions

Package node 12 and latest compatible bcrypt

---

.meteor/packages
package-lock.json

This makes `meteor run` and `meteor npm i` not dirty the tree for me.

Clean up a couple package things

---

imports/client/components/GuessQueuePage.tsx
imports/client/components/PuzzleListPage.tsx

Use URLSearchParams to manage query strings

---

client/stylesheets/index.css
client/stylesheets/puzzle.scss

Put chat CSS all in one place

---

imports/client/components/Puzzle.tsx
imports/client/components/PuzzleListPage.tsx
imports/client/components/PuzzlePage.tsx

Consistently treat puzzles with more answers than expected as solved

---

imports/client/components/NotificationCenter.tsx

If:
* There's a ServiceConfiguration for Discord configured on the server, and
* the `disable.discord` feature flag is not flipped, and
* the user has not linked their Discord account to their jolly-roger account:
Then:
* We will show a notification to nudge the user to get added to the Discord

Add notification to prompt people to get invited to Discord

---

imports/server/discord-client-refresher.ts

I think this makes the code easier to follow and more correct, but I'm curious if other people agree.

Restructure Discord client refresher

---

imports/client/components/Celebration.tsx

Close celebration on esc press

---

imports/client/components/HuntListPage.tsx
imports/client/components/HuntProfileListPage.tsx
imports/client/components/ProfileList.tsx
imports/client/discord.ts
imports/lib/active-operator-role.ts
imports/lib/models/discord_cache.ts
imports/lib/roles.ts
imports/lib/schemas/hunts.ts
imports/server/addUserToDiscordRole.ts
imports/server/discord.ts
imports/server/hunts.ts
imports/server/profile.ts

I think this will do the thing. It's not the prettiest code but it should get the job done.

Support per-hunt Discord role

---

imports/client/components/UserInvitePage.tsx
imports/lib/active-operator-role.ts
imports/lib/roles.ts
imports/server/hunts.ts

Add a bulk invite form for operators

---

imports/server/discord-client-refresher.ts

Minor thing, but these can all change

Track changes to Discord username or discriminator

---

imports/client/components/CallLinkBox.tsx
imports/client/components/CallSection.tsx
imports/client/components/ChatPeople.tsx
imports/lib/discord.ts
imports/lib/models/profiles.ts
imports/lib/schemas/discord_account.ts
imports/lib/schemas/profiles.ts

Hopefully this does better at disambiguating speakers than a single letter from
the user's display name, and has better reach than Gravatar (which seems to
only cover like 4% of our team).

Use Discord avatars if available

---

imports/client/components/GuessQueuePage.tsx
imports/client/components/ProfileList.tsx
imports/client/components/PuzzleListPage.tsx

Override ctrl-f to focus search bars

---

imports/client/components/PuzzleListPage.tsx

Later on in hunt, it's often the case that you have a bazillion solved
puzzles and like 10 unsolved ones, and you'd like to toggle that "show
solved" button.  But then in another moment you're trying to find the
link to the puzzle that gave you a particular answer or something, and
you can't quite remember the name or if you've solved it or not, and so
you have to toggle show solved again, and then you have to toggle it
back again after you're done searching.
That is a drag.  If your search would return no matches, it's more
useful to show *something* that matches the search string but not the
"show solved" constraint, if such a thing exists.
So this patchset does that -- if filtering by search term gives nonzero
results, but additionally filtering by solve state returns no results,
we'll …

PuzzleListPage search: show solved if no unsolved matches found

---

imports/client/components/AudioConfig.tsx
imports/client/components/CallLinkBox.tsx
imports/client/components/ChatPeople.tsx

This reduces the number of callbacks and makes the flow of code a little
easier to follow. (It should have no impact on behavior.)

Switch to async/await for promises in audio code

---

cloudformation/jolly-roger.yaml

Biggest change is the final deprecation of py2, which I didn't actually realize we were still depending on, whoops.

Upgrade to focal

---

cloudformation/jolly-roger.yaml

(I think this wasn't supported when I first wrote this configuration, but ALB can do these redirects now)

Move the HTTP => HTTPS redirect into ALB

---

imports/server/mediasoup.ts

Fixes the following crash when IPv6 is not available:
```
W20211231-12:16:52.077(-8)? (STDERR) /Users/evan/.meteor/packages/promise/.0.12.0.1j7k6ey.ay9e++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:218
W20211231-12:16:52.077(-8)? (STDERR)       throw error;
W20211231-12:16:52.077(-8)? (STDERR)       ^
W20211231-12:16:52.077(-8)? (STDERR)
W20211231-12:16:52.077(-8)? (STDERR) Error: queryAaaa ECONNREFUSED myip.opendns.com
W20211231-12:16:52.077(-8)? (STDERR)     at QueryReqWrap.onresolve [as oncomplete] (internal/dns/promises.js:172:17)
W20211231-12:16:52.077(-8)? (STDERR)  => awaited here:
W20211231-12:16:52.077(-8)? (STDERR)     at Function.Promise.await (/Users/evan/.meteor/packages/promise/.0.12.0.1j7k6ey.ay9e++os+web.browser+web.browse …
```

Don't crash when we can't resolve our IP

---

imports/client/components/CallSection.tsx

Apparently support for the MediaStream active event is...spotty. So
instead, have ConsumerManagers explicitly call back into PeerBox with
tracks when they get them, and have a callback in PeerBox manage both
adding/removing tracks from the stream and tracking when there are a
non-0 number of tracks.

Fix receiving audio on non-Chrome browsers

---

imports/client/components/PuzzlePage.tsx

Fix incorrect dep

---

Dockerfile

When I split the build and test steps into separate Docker stages, I
inadvertently bypassed running the tests at all, because nothing from
the test stage was copied into the final production stage. Docker was
smart enough to skip those steps entirely.
I want to force them to run without un-parallelizing the test + build
steps, so make sure we use the output of the test step by copying the
scripts directory out of it. It's a bit of a roundabout way to do
things, since we don't actually change the scripts directory at all in
that stage, but it creates the dependency we care about.

Fix tests in CI build

---

imports/client/components/HuntListPage.tsx

If the Jolly Roger Discord bot has been added to more than one guild,
channels and roles from all of those guilds will be available in the
Discord cache for selection when creating/editing a hunt, which is not
the behavior we want.
This doesn't come up often in practice because generally Jolly Roger
runs in a single-guild setup, but this gives us future proofing (and
also lets us slightly simplify our role logic).

Narrow role/channel listings to selected guild

---

imports/client/components/FirehosePage.tsx

We definitely have some at least soft-deleted puzzles in our history.
It's not a bad idea to also be resilient to hard-deleted puzzles too.

Make FirehosePage handle deleted puzzles

---

imports/client/components/HuntApp.tsx

Fixes #552.
Untested, but I'm 90% sure this will do the thing.

Fix puzzle list redirect

---

imports/server/gdrive.ts

In production, we seem to have some documents that don't connect back to
hunts still in existence. Try to be a little more defensive of this
situation.

Handle errors caused by deleted hunts

---

imports/client/components/PuzzlePage.tsx

There's a couple places where we need height changes from other children
to trigger scrolling in another child of a component.  We had been
dispatching these events via callbacks that accessed refs, but it turns
out that under certain render batching and ordering, we would fail to
deliver the callback to the pane that needed to be scrolled.
What's more, when we miss delivering such an event, the browser
generates a scroll event on the pane to be scrolled which we must
interpret as the user scrolling the pane to that target, breaking
the previous scroll offset, and causing us to no longer keep the
chat backlog sticky at the bottom.
This patchset attempts to fix the misbehavior by adding a ref (because
we must act within *this* render batch, not later due to a setState) for
keeping track of …

Defer layout effect callback that we can't fire due to null refs

---

tests/acceptance/authentication.tsx
tests/acceptance/lib.ts
tests/acceptance/smoke.tsx

Because we're resetting the database, we can take advantage of
`provisionFirstUser` to make ourselves an admin account, and then use
those admin privileges to make ourselves an operator.
(Following up on a suggestion from @zarvox in #654)

Use existing methods in tests

---

imports/client/components/RootRedirector.tsx

This avoids breaking the back button.

Make root redirects replacements

---

.github/workflows/build.yml
Dockerfile
package-lock.json
package.json

Reverts deathandmayhem/jolly-roger#674
```
/bin/sh: 1: /built_app/scripts/run_jolly_roger.sh: not found
```

Revert "Use eslint-formatter-gha to annotate diff with lint errors"

---

cloudformation/jolly-roger.yaml

Cloudformation fixups

---

.gitignore

The new Meteor Toolbox extension for VS Code seems to generate some
additional detritus.

Add some additional files to .gitignore

---

package-lock.json
package.json

(dependabot isn't smart enough to pull both of them at the same time.)

Take fontawesome updates together

---

imports/client/components/PuzzlePage.tsx

Before this change, it was possible that if you hit `F5` to reload
the page while you had a puzzle page open, you might hit a race
condition where:
* `activePuzzle` was still `undefined` despite the various subscriptions
finishing loading, because
* `activePuzzle` did not declare a dep on `puzzleDataLoading` and the
cached value (computed *before* the sub data had arrived) was
initially undefined, and
* `useTracker` had not yet scheduled a rerun of that particular
invalidated computation, because
* the subscription completion that had triggered the rerender of
PuzzlePage was not the puzzle data subscription, but a different sub
Once hit, this would cause an exception in rendering where we'd attempt
to access `activePuzzle.title`, which was made possible in part by a
faulty non-null type …

Fix an incorrect missing dep on PuzzlePage

---

imports/lib/schemas/typedSchemas.ts
imports/lib/schemas/validators.ts
package-lock.json
package.json

This requires a little rooting around to get at the appropriate types, but it is doable.

Upgrade simpl-schema to the latest version

---

imports/server/GlobalHooks.ts
imports/server/hooks/ChatHooks.ts
imports/server/hooks/HooksRegistry.ts
imports/server/hooks/Hookset.ts
imports/server/methods/addPuzzleAnswer.ts
imports/server/methods/createHunt.ts
imports/server/transitionGuess.ts
tests/acceptance/chatHooks.ts
tests/acceptance/lib.ts
tests/acceptance/profiles.tsx
tests/main.ts

They were easy and had been sitting for a while. I had some aspirations of leaving these for newcomers, but we're not really getting newcomers, so we might as well just do them.

Fix two bitesized bugs

---

imports/client/components/ProfileList.tsx

By applying De Morgan's Law, we can make this much more readable.

Clarify the match criteria in ProfileList

---

imports/server/gdriveDocumentWatcher.ts

If the feature flag is disabled, we can avoid attempting to import ngrok at all, which prevents a noisy error around unhandled promise rejection when running without optional dependencies.

Do earlier exit in gdriveDocumentWatcher if feature flagged off

---

imports/server/gdriveChangeFetcher.ts

This logic attempted to avoid updating the token record if another process had gotten to it first, but this introduced two problems. First, we didn't always use the token that we got back from the database. Second, if another process _had_ gotten to it first, then our query wouldn't match any existing record, and we would try to insert (which would be a duplicate key error).

Fix update to DriveChangesPageTokens

---

imports/client/components/CallSection.tsx

Render the remote mute modal outside the OverlayTrigger

---

imports/client/components/PuzzlePage.tsx

Guess modal cleanups

---

imports/client/components/NotificationCenter.tsx

Before:
and after:
I'm not totally in love with it, but I think it's at least as good as the current layout, and I like that it is slightly more compact and reuses what we've now made into a common design language.

Use direction/confidence components in notifications

---

imports/client/components/Avatar.tsx
imports/client/components/RTCDebugPage.tsx

Fix a minor error in #691 that causes a 1px vertical misalignment of avatars.

Fix Discord avatar vertical alignment

---

imports/server/addUsersToDiscordRole.ts
imports/server/discordClientRefresher.ts
imports/server/garbage-collection.ts
imports/server/gdrive.ts
imports/server/gdriveActivityFetcher.ts
imports/server/hooks/ChatHooks.ts
imports/server/hooks/HooksRegistry.ts
imports/server/mediasoup.ts
imports/server/methods/configureCollectGoogleAccountIds.ts
imports/server/methods/configureEnsureGoogleScript.ts
imports/server/methods/configureOrganizeGoogleDrive.ts
imports/server/methods/createFixtureHunt.ts
imports/server/methods/createHunt.ts
imports/server/methods/linkUserDiscordAccount.ts
imports/server/methods/linkUserGoogleAccount.ts
imports/server/onExit.ts
tests/acceptance/lib.ts

This was an attempt to avoid the no-await-in-loop linter rule, but because of the chaining, it creates massive stack traces with each loop showing up as an "awaited here" line.
If we want serialism, we shouldn't sneak past the linter to get it.

Eliminate reduce-over-promise pattern

---

imports/client/components/PuzzlePage.tsx
imports/lib/dingwordLogic.ts
imports/server/hooks/ChatNotificationHooks.ts

This is kinda a starting point for discussion.  I'm not totally sold on this specific appearance for this, but I do like the idea of having "the message that summoned me to a puzzle" having something that indicates the specific message in the log as noteworthy.
I'm open to feedback on the idea, including "this is ugly/a bad idea; don't do this".  Thoughts?

Highlight messages that trip your dingwords

---

imports/client/components/FirehosePage.tsx

While we're doing layout, let's render with a more readable grid layout.  Does actual formatting on each message and supports both v1 and v2 chat messages, which *is* a bit more expensive -- I profiled it as taking about 3x as much wall-clock time per formatted message on a (separate, smaller) dataset on my M1 MBA as the current v1 chat (which doesn't do formatting at all).  Which is a bit.
However, I think this is probably good enough -- the worst of the FirehosePage is the initial loading time and streaming all the ChatMessage records from the server, which today for the 2022 takes 18 seconds, whereas rendering takes about 3 seconds for ~30000 chat messages.  The improved readability of having a more tabular structure seems plausibly worthwhile?  Especially since I expect most …

Rework FirehosePage for chatmessage v2 

---

imports/lib/dingwordLogic.ts

It doesn't make sense to highlight your dingwords in your own messages. You know what you wrote already.

Avoid highlighting any message that was sent by you

---

imports/client/components/GuessQueuePage.tsx

Search over submitter's displayName in GuessQueuePage

---

imports/client/components/ChatMessage.tsx
imports/client/components/NotificationCenter.tsx
imports/client/components/PuzzlePage.tsx
imports/methods/sendChatMessage.ts
imports/server/hooks/ChatHooks.ts
imports/server/hooks/DiscordHooks.ts
imports/server/methods/addPuzzleAnswer.ts
imports/server/methods/createGuess.ts
imports/server/methods/index.ts
imports/server/methods/sendChatMessage.ts
imports/server/sendChatMessageInternal.ts
imports/server/transitionGuess.ts

Cleanup requested as a follow-up after #1432.

Rename away all the V2s

---

cloudformation/jolly-roger.yaml
imports/client/components/CallSection.tsx
imports/client/hooks/useCallState.ts
imports/lib/models/mediasoup/Transports.ts
imports/server/mediasoup.ts

This adds client UI when it detects that the call is in a bad state (fixes #1366) and re-introduces TURN support to bust through particularly aggressive firewalls (fixes #1363).

Improve RTC robustness

---

imports/server/gdriveActivityFetcher.ts

When we have a lock to fetch Google Drive activity, we attempt to continually renew it. But if, for some reason, that renewal fails, we should bail and attempt to reacquire the lock. Previously, we would blithely go on about our business and continue trying to renew the lock that we had already lost, resulting in both two processes attempting to fetch activity history and a lot of error noise from the failed renewals.

Unwind Google Drive fetcher if lock is preempted

---

client/stylesheets/_theme.scss

Cleanup Bootstrap breakpoint hack

---

imports/server/hooks/DiscordHooks.ts
imports/server/hooks/HooksRegistry.ts
imports/server/hooks/Hookset.ts
imports/server/methods/updatePuzzle.ts

Fixes #1355.
Here's what it looks like:
As a note, I considered pulling the Google Doc rename mechanism into a hook but decided against it as right now if one hook fails it blocks any subsequent hooks from running, which feels like it is probably a bug for another day.

Announce renames to the announce channel

---

imports/Flags.ts
imports/client/components/SetupPage.tsx
imports/lib/models/FeatureFlags.ts
imports/methods/setFeatureFlag.ts
imports/server/methods/setFeatureFlag.ts
imports/server/migrations/25-remove-slack-featureflag.ts
imports/server/migrations/26-remove-subcounter-feature-flags.ts
imports/server/migrations/40-cleanup-celebrations.ts
imports/server/migrations/50-upconvert-chatmessage-content.ts

Some small things I noticed we could make better while I was poking around at various things

Feature flag improvements

---

client/stylesheets/_theme.scss
imports/Logger.ts
package-lock.json
package.json

And reformat (only two files changed).

Upgrade prettier to 3.6.2
